### ISSUE TITLE
route specification does not work when pubsub component is provided by Apache Pulsar

### ISSUE THREAD

**Issue by irhawks** [dapr/components-contrib#1004]
Environment: dapr standalone

```console
CLI version: 1.2.0 
Runtime version: 1.2.2
```

Running  a publish-subscribe test application as described in <https://github.com/dapr/quickstarts/tree/master/pub-sub>  works well under default dapr runtime ( initialized by `dapr init`). However, when changing pubsub component provider to pulsar, dapr always send message to route '/' and thus raise a requested URL was not found exception.

python3 script (app.py) (copy from <https://github.com/dapr/quickstarts/blob/master/pub-sub/python-subscriber/app.py>)

```python
import flask
from flask import request, jsonify
from flask_cors import CORS
import json
import sys

app = flask.Flask(__name__)
CORS(app)

@app.route('/dapr/subscribe', methods=['GET'])
def subscribe():
    subscriptions = [{'pubsubname': 'pubsub', 'topic': 'A', 'route': 'A'}, {'pubsubname': 'pubsub', 'topic': 'C', 'route': 'C'}]
    return jsonify(subscriptions)

@app.route('/A', methods=['POST'])
def a_subscriber():
    print(f'A: {request.json}', flush=True)
    print('Received message "{}" on topic "{}"'.format(request.json['data']['message'], request.json['topic']), flush=True)
    return json.dumps({'success':True}), 200, {'ContentType':'application/json'} 

@app.route('/C', methods=['POST'])
def c_subscriber():
    print(f'C: {request.json}', flush=True)
    print('Received message "{}" on topic "{}"'.format(request.json['data']['message'], request.json['topic']), flush=True)
    return json.dumps({'success':True}), 200, {'ContentType':'application/json'} 

app.run()

```

```sh
dapr run --app-id python-subscriber --app-port 5000 python3 app.py
dapr publish --publish-app-id python-subscriber --pubsub pubsub --topic C --data-file message_a.json
```

1. pubsub provided by a pulsar standalone instance, raise error for route '/'

`~/.dapr/components/pubsub.yml`

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.pulsar
  version: v1
  metadata:
  - name: host
    value: "172.17.0.1:6650"
  - name: enableTLS
    value: "false"
```

```console
== APP == 127.0.0.1 - - [09/Jul/2021 07:35:16] "POST / HTTP/1.1" 404 -
ERRO[0067] non-retriable error returned from app while processing pub/sub event 11d9af1a-5624-4d07-9a10-3edb0630ef88: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
. status code returned: 404  app_id=python-subscriber instance=HomePC scope=dapr.runtime type=log ver=1.2.2
```

2. pubsub provided by redis **outputs as expected (~/.dapr/components/pubsub.yml)**

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
```

result 

```console
== APP == C: {'traceid': '00-f9e0baa72290c20a7b81ff41f8e32095-52686d383ea8857f-01', 'source': 'python-subscriber', 'specversion': '1.0', 'datacontenttype': 'application/json', 'type': 'com.dapr.event.sent', 'topic': 'C', 'pubsubname': 'pubsub', 'data': {'messageType': 'A', 'message': 'Message on A'}, 'id': 'c0f1a284-f2ef-413f-a518-7e50ab4b382a'}
== APP == Received message "Message on A" on topic "C"
== APP == 127.0.0.1 - - [09/Jul/2021 07:54:59] "POST /C HTTP/1.1" 200 -
```

3. pubsub provided by kafka ( KoP on pulsar) **outputs as expected (~/.dapr/components/pubsub.yml)**

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
      # Kafka broker connection setting
    - name: brokers
      value: "172.17.0.1:9092"
    - name: authRequired
      value: "false"
    - name: maxMessageBytes
      value: 1024
```

result: 

```console
== APP == C: {'id': '204fab80-e5c0-4745-b8e9-80b5590a2006', 'datacontenttype': 'application/json', 'source': 'python-subscriber', 'type': 'com.dapr.event.sent', 'data': {'messageType': 'A', 'message': 'Message on A'}, 'specversion': '1.0', 'topic': 'C', 'pubsubname': 'pubsub', 'traceid': '00-612c9757ed4dd72eae1189442eb6a477-b7145f0143707262-01'}
== APP == Received message "Message on A" on topic "C"
== APP == 127.0.0.1 - - [09/Jul/2021 07:57:15] "POST /C HTTP/1.1" 200 -
```
