### ISSUE TITLE
Azure Service Bus binding improvements

### ISSUE THREAD

**Issue by alanwales** [dapr/components-contrib#102]
I didn't see these documented anywhere but it stumped me for a while so might be good to add it to the samples or documentation.

When listening to an [output binding from Azure Service Bus](https://github.com/dapr/docs/blob/24781faf9050ead710877c6f779ac6a0ff3886b6/concepts/bindings/specs/servicebusqueues.md), Dapr expects to POST the queue message to the following url:

http://localhost/orders

First confusion: This has to match the name of the component (didn't seem obvious at first: how would you specify a url with multiple parts like http://localhost/api/v1/orders?)

Second confusion: The connectionString has to start with Endpoint=sb://, the docs suggest it starts with sb:// but this throws an index out of range exception

Sample:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orders
  namespace: "local"
spec:
  type: bindings.azure.servicebusqueues
  metadata:
  - name: connectionString
    value: Endpoint=sb://
```

Third confusion: when implementing the endpoint an OPTIONS call is made first, presumably to see which http verbs are supported. Enabling CORS does not solve this: I had to add a separate options endpoint before Dapr could make the POST call, otherwise the api gives the following error in .net core 3.0:

Executing endpoint '405 HTTP Method Not Supported'

Would be good to document this somewhere if this is really the correct behaviour.

```c#
        [Route("orders")]
        [HttpPost]
        public async Task<IActionResult> Post_Messages()
        {
            // insert message handling logic here
            return Ok();
        }
 
        [Route("orders")]
        [HttpOptions]
        public async Task<IActionResult> Options_Messages()
        {
            Response.Headers.Add("Allow", $"{HttpMethod.Options.ToString().ToUpperInvariant()}, {HttpMethod.Post.ToString().ToUpperInvariant()}");
            return await Task.FromResult(NoContent());
        }
```
