### ISSUE TITLE
how to trigger circuitBreakerRules when i use sentinel-go middleware in dapr?

### ISSUE THREAD

**Issue by sd797994** [dapr/components-contrib#1026]
@beiwei30 Hi~
I wanted to test sentinel's circuitBreakerRules, but they didn't work。
According to this document【https://docs.dapr.io/reference/components-reference/supported-middleware/middleware-sentinel/】, I wrote my Component and injected it into my application through Configuration. my test environment is k8s

this is my config document:

```yaml
------------------------------------
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sentinel
  namespace: default
spec:
  type: middleware.http.sentinel
  version: v1
  metadata:
  - name: appName
    value: "rules"
  - name: logDir
    value: "/tmp"
  - name: circuitBreakerRules
    value: >-
      [
        {
          "resource": "POST:/v1.0/invoke/callservice/method/call/callmyself",
          "threshold": 1, 
          "strategy": 2, # ErrorCount
          "minRequestAmount": 0,
          "statIntervalMs": 10000, # 10‘s
          "retryTimeoutMs": 60000 # 60‘s
        }
      ]
------------------------------------
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: sentinelconfig
  namespace: default
spec:
  httpPipeline:
    handlers:
      - name: sentinel
        type: middleware.http.sentinel
------------------------------------
apiVersion: apps/v1
...
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "callservice"
        dapr.io/app-port: "80"
        dapr.io/config: "sentinelconfig"
...
-----------------------------------
```

In this webapi: /call/callmyself, I simulated a 50% error callback rate. return 500 code,but they circuitBreaker didn't work,why?
