### ISSUE TITLE
Sidecar crashing when state.sqlserver included

### ISSUE THREAD

**Issue by andycwk** [dapr/components-contrib#1036]
## Expected Behavior

When I attempted to include a sql server state component in my Dapr app configuration within a local Kind Kubernetes cluster the Dapr sidecar for my service should initiate the state store and the Dapr sidecar should spin up and start servicing requests for the associated service.

## Actual Behavior
The sidecar starts to initialise the state component, but a panic is thrown and the sidecar spins into a spiral of restarts.

The following logs are generated..
[dapr-sidecar.log](https://github.com/dapr/components-contrib/files/6896587/dapr-sidecar.log)

After discussion within Discord it was suggested that the sql dependency may require updating.. a quick check shows that this looks like the most likely issue.

![Screenshot_2021-07-28_at_22 15 27](https://user-images.githubusercontent.com/2248787/127399645-bb64e1b4-9ac6-4572-a31d-c326e9c81114.png)

## Steps to Reproduce the Problem
Install the latest version of Dapr (v1.3.0 at point of raising this issue), ensure a sidecar is being injected into a service pod and then add a sql state component - I had the following state config..

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: idea-state
  namespace: default
spec:
  type: state.sqlserver
  version: v1
  metadata:
    - name: connectionString
      value: Server=xxxxxxx.database.windows.net;Database=xxxxx-xxxx;User ID=uxxx;Password=xxxx;
    - name: tableName
      value: state # Required.
    - name: schema
      value: "idea" # Optional. defaults to "dbo"
```

As above I guess :/ 

## Release Note

RELEASE NOTE: **UPDATE** Bumped go-mssqldb dependency version
