### ISSUE TITLE
OPA HTTP Middleware Does Not Block Requests

### ISSUE THREAD

**Issue by nstrause1** [dapr/components-contrib#1146]
Hello, I'm trying to get the OPA Middleware to work, but it's not behaving like I would expect.

I'm creating a simple deny all policy and configuring one of my services to use that middleware:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: poc-opa
spec:
  type: middleware.http.opa
  version: v1
  metadata:
    - name: rego
      value: |
        package http

        default allow = false
```

I'm then invoking this service from another Dapr service using the service invocation API. I would expect any request to be denied. It seems like all requests are still being allowed though.

I do see in logs that the OPA middleware is being loaded and when applying the uppercase middleware, it functions as expected. The OPA middleware seems to have no effect, and no errors are being logged.

```
time="2021-09-14T19:37:50.2008172Z" level=info msg="enabled middleware.http.uppercase/ http middleware" app_id=bar-service instance=901cc2ac7503 scope=dapr.runtime type=log ver=1.4.0-rc.7
time="2021-09-14T19:37:50.2030102Z" level=info msg="enabled middleware.http.opa/ http middleware" app_id=bar-service instance=901cc2ac7503 scope=dapr.runtime type=log ver=1.4.0-rc.7
```

Am I misunderstanding what the OPA middleware is supposed to do? Is there any sort of working example where the OPA middleware is enforcing a policy you can point me to?

[Here's the example project I'm working with](https://github.com/nstrause1/dapr-opa-test)
