### ISSUE TITLE
Specify Default Values in Local environment variables (secretstores.local.env) yaml?

### ISSUE THREAD

**Issue by fbridger** [dapr/components-contrib#1170]
## Does the Local environment variables (secretstores.local.env) supports specifying default values?
I am trying to include Secrets as ENV VARs for Local Development purposes and I was wondering if there was a way to specify default values if ENV VARs does not exist.

I don't know if this is currently supported but I was thinking that default values could be specified like this:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: bill360-secret-store
  namespace: default
spec:
  type: secretstores.local.env
  version: v1
  metadata:
  - name: defaultValues
    value: 
    - ENV_VAR_NAME_1=ENV_VAR_DEFAULT_VALUE_1
    - ENV_VAR_NAME_2=ENV_VAR_DEFAULT_VALUE_2
```
