### ISSUE TITLE
[Proposal] middleware with WASM

### ISSUE THREAD

**Issue by daixiang0** [dapr/components-contrib#1171]
## Describe the proposal

As [middleware doc](https://docs.dapr.io/developing-applications/middleware/) said, implement a new one needs many steps. If we implement WASM for it, developers can use and change custom middleware anytime, no need to wait for PRs to merge. It is great practice and pattern I think.

Also, developers can easily change middleware logic without restart Dapr.

In total, implement middleware with WASM has the following benefits:
- more friendly way for developers to custom middleware
- support dynamic load

**Comment by yavuztor** [comment]
@daixiang0 that would be a great feature. I have been thinking about this as well. Good news is that today at [DaprCon Day 1](https://youtu.be/7ax-ltJjM58) , @yaron2 mentioned that it is getting in the roadmap. Looking forward to seeing this feature land on a release.

**Comment by richgo** [comment]
The team over at Gloo have done a great job on enovy with their wasme cli: https://docs.solo.io/web-assembly-hub/latest/reference/cli/wasme/. Something similar would work pretty well for DAPR?

**Comment by daixiang0** [comment]
@richgo thanks for your great demo!

Recently I am thinking of it and share the draft here:

1. WASM can do more things than HTTP, `middleware.wasm` or `middleware.http.wasm`? I choose the latter as it is easier to start and I do not find a good use case outside HTTP for now.
2. Should we use the envoy interface or support it? I prefer to support it. The current middleware interface is simple but useful, meeting users' basic needs. The envoy interface is more powerful but harder to start and implement, also maintaining envoy interface may be a big job once modified. So I design it as `middleware.http.wasm.basic` and `middleware.http.wasm.enovy`, split them for better maintenance and user experience.
3. Where are the wasm files stored? I choose the local file system, and support monitor, so that we can get dynamic middleware. For remote stores, monitor is a big issue. I think we need to create a store monitor interface to support different stores, and still need to download onto the local file system, so let's start from local file system first.

Here's a very initial rough draft to iterate on:
component format:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: wasm-basic
spec:
  type: middleware.http.wasm.basic
  version: v1
  metadata:
  - name: dir
    value: <path to wasm dir>
    runtime: <wasm runtime>
```
Load and monitor all wasm files under specified dir. One dir should only include files written by the same wasm runtime.

Dapr config:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  httpPipeline:
    handlers:
    - name: wasm-basic
      type: middleware.http.wasm.basic
```

component format:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: wasm-enovy
spec:
  type: middleware.http.wasm.enovy
  version: v1
  metadata:
  - name: path
     value: <path to wasm>
     runtime: <wasm runtime>
     config: <custom config in json format>
```

Dapr config:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  httpPipeline:
    handlers:
    - name: wasm-enovy
      type: middleware.http.wasm.enovy
```
