### ISSUE TITLE
When Consul is used as a name resolution component, the same appid cannot achieve load balancing, and the dapr started later will overwrite the previous dapr

### ISSUE THREAD

**Issue by cysnet** [dapr/components-contrib#1199]
![image](https://user-images.githubusercontent.com/35944271/137460463-52c3f9e9-672e-428d-892d-8cd6e1261ace.png)
I started two backend services on two dapr instances, but only the backend started later in consul, and load balancing cannot be achieved.
One instance ip is 192.168.43.131, another is 192.168.43.132. But only the one started later can be registed in consul.

And the config of the two dapr instances have the same content just as below:
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  nameResolution:
    component: "consul"
    configuration:
      client:
        address: "192.168.43.133:8500"
      selfRegister: true
```
