### ISSUE TITLE
Warning generated by SMTP binding when username and password are both set.

### ISSUE THREAD

**Issue by wmeints** [dapr/components-contrib#1255]
## Expected Behavior

The SMTP binding generates a warning when no username and password are provided.

## Actual Behavior

The SMTP binding generates a warning when username AND password are set.

## Steps to Reproduce the Problem

1. Create a binding configuration for SMTP:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sendmail
spec:
  type: bindings.smtp
  version: v1
  metadata:
  - name: host
    value: localhost
  - name: port
    value: 4025
  - name: user
    secretKeyRef:
      name: smtp.user
      key: smtp.user
  - name: password
    secretKeyRef:
      name: smtp.password
      key: smtp.password
  - name: skipTLSVerify
    value: true
auth:
  secretStore: trafficcontrol-secrets
```

2. Start an app with `dapr run`.

## Release Note

RELEASE NOTE:
