### ISSUE TITLE
Kafka pub/sub not working with DAPR version 1.5

### ISSUE THREAD

**Issue by jagjeetst** [dapr/components-contrib#1350]
# Kafka run out of available brokers

**Comment by artursouza** [comment]
Can you provide more details on your scenario? Also, some logs can help.

**Comment by yaron2** [comment]
Also please paste your component YAML here.

**Comment by jagjeetst** [comment]
> Can you provide more details on your scenario? Also, some logs can help.

**Error facing** 
time="2021-12-01T11:30:34.2787635+05:30" level=fatal msg="process component pubsub error: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)" app_id=notifications instance=softobiz-jagjeet scope=dapr.runtime type=log ver=1.5.0

Could not update sidecar metadata for cliPID: PUT http://127.0.0.1:3600/v1.0/metadata/cliPID giving up after 5 attempts

DAPR version 1.5
dapr init --runtime-version=1.5.0


But If I have 
CLI version: 1.5.0
Runtime version: 1.4.0

then kafka pubsub starts working.


Pubsub file

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: dev
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "pkc-XXXXXXXXXXXX:9092"
  - name: clientID
    value: "microservices"
  - name: authRequired
    value: "true"
  - name: saslUsername    
    value: "D5XXXXXXXXXXN"
  - name: saslPassword
    value: "fjwtLXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXrRSN"
  - name: maxMessageBytes
    value: 2048

**Comment by jagjeetst** [comment]
Hello @yaron2  @artursouza  , any update on above please. I am in middle of this implementation. 
Thanks.

**Comment by jagjeetst** [comment]
@yaron2  @artursouza  , I was trying on Discord , if we can connect there. I have sent you request from username jagjeet. 
If you are more active on that, we can discuss there too. Thanks.

**Comment by yaron2** [comment]
This happens when running locally with the Dapr CLI, am I correct?

**Comment by pkedy** [comment]
> process component pubsub error: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

This error message from the underlying library (Sarama) occurs if cannot connect to brokers in general. Its a little misleading but I would make sure the credentials are correct.

Outside of that, id does seem like there were some changes to the component's settings, but I could see where there could be an issue. I'll take a second look though.

**Comment by jagjeetst** [comment]
> This happens when running locally with the Dapr CLI, am I correct?

Yes, when running on locally, this issue starts coming.

**Comment by jagjeetst** [comment]
> 

Is there any issue with library (Sarama) that creates issue with DAPR runtime version 1.5 but works fine for DAPR runtime version 1.4 ?

**Comment by pkedy** [comment]
I have tried to reproduce this using 1.5.1 and was not successful. My settings are identical to your except for I am not using SASL for auth (thus authRequired is "false").

I also tried setting `authRequired` to "true" and setting `saslUsername` and `saslPassword` to non-empty strings. I can confirm that bad authentication/credentials will manifest as this error.

```
WARN[0000] error initializing pub sub pubsub.kafka/v1: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
```

Can you confirm that your SASL credentials are correct? What is strange to me is that between 1.4 and 1.5, the SASL code did not change.

**Comment by jagjeetst** [comment]
yes , @pkedy   , SASL credentials were correct and how I can confirm them is, when I run this command in powershell, 
**dapr init --runtime-version=1.4.0**
then after changing runtime version of DAPR, pub/sub starts working for me with given SASL username and password with authRequired True

on the other side when I change runtime version for DAPR > **dapr init --runtime-version=1.5.0**
then with the same credentials, DAPR pub/sub stops working for me.  And kakfa run out of available brokers issue starts coming up. 

Can you please try that one. Thanks.

**Comment by mbimbij** [comment]
I face the very same issue trying the pubsub example with kafka module:

```
dapr run --app-id node-subscriber --app-port 3000 node app.js
[...]
FATA[0005] process component pubsub error: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)  app_id=node-subscriber instance=joseph-ThinkPad-T480 scope=dapr.runtime type=log ver=1.5.1
```

Here is the config of my kafka pubsub component:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers # Required. Kafka broker connection setting
      value: "http://localhost:9092"
    - name: consumerGroup # Optional. Used for input bindings.
      value: "group1"
    - name: clientID # Optional. Used as client tracing ID by Kafka brokers.
      value: "my-dapr-app-id"
    - name: authRequired # Required.
      value: "false"
    - name: maxMessageBytes # Optional.
      value: 1024
    - name: consumeRetryInterval # Optional.
      value: 200ms
```
