### ISSUE TITLE
Redis configuration store notifies the app twice

### ISSUE THREAD

**Issue by yaron2** [dapr/components-contrib#1352]
When subscribing to a key update, the app gets notified twice.

How to reproduce:

Use the following client code:

```go
       // Establish gRPC connection
	ctx, ctxCancel := context.WithTimeout(context.Background(), 1*time.Second)
	conn, err := grpc.DialContext(
		ctx,
		fmt.Sprintf("localhost:%s", os.Getenv("DAPR_GRPC_PORT")),
		grpc.WithInsecure(),
	)
	if err != nil {
		ctxCancel()
		panic(err)
	}

	// Create Dapr client
	c := pb.NewDaprClient(conn)

	// Watch configuration item
	s, err := c.SubscribeConfigurationAlpha1(context.TODO(), &pb.SubscribeConfigurationRequest{
		StoreName: "redis",
		Keys: []string{
			"account_name",
		},
	})
	if err != nil {
		panic(err)
	}

	for {
		update, err := s.Recv()
		if err != nil {
			panic(err)
		}

		if update != nil && update.Items != nil {
			fmt.Printf("Key: %s, Value: %s, Version: %s\n", update.Items[0].Key, update.Items[0].Value, update.Items[0].Version)
		}
	}
```

Dapr component:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis
spec:
  type: configuration.redis
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
```

Add key:

```
redis-cli -p 6379
set account_name wookie||v1.0
```

Run Dapr:

```
dapr run --app-id configdemo --components-path ./components  -- go run main.go
```

Change key:

```
redis-cli -p 6379
set account_name wookie2||v1.1
```

See the app notified twice.
