### ISSUE TITLE
"Bind variables cannot be used for table names" with cassandra state component 

### ISSUE THREAD

**Issue by mbimbij** [dapr/components-contrib#1387]
close #1388 

## Expected Behavior
I should be able to get and post simple data

## Actual Behavior

When trying to query or insert data into cassadra statestore, i get:
```
{"errorCode":"ERR_STATE_SAVE","message":"failed saving state in state store statestore-cassandra: Bind variables cannot be used for table names"}
```
or
```
{"errorCode":"ERR_STATE_GET","message":"fail to get toto from state store statestore-cassandra: Bind variables cannot be used for table names"}
```

## Steps to Reproduce the Problem
Reproduced in self-hosted mode

here is the content of the yaml component file:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore-cassandra
spec:
  type: state.cassandra
  version: v1
  metadata:
  - name: hosts
    value: localhost
```
I ran the dapr sidecar in a standalone mode:
`dapr run --app-id test --dapr-http-port 3500`

then i get / post data:
```
curl localhost:3500/v1.0/state/statestore-cassandra/toto -w "\n"
curl -XPOST -H "content-type: application/json" localhost:3500/v1.0/state/statestore-cassandra -d '[{"key":"toto","value":{"plop":"42"}}]' -w "\n"
```

## Release Note

RELEASE NOTE: **FIX** Bug in cassandra component.

## Comment

I am not a go developer, but in functions  i think the component should probably use `fmt.Sprintf`, as done in the function `tryCreateKeyspace`, instead of what looks like a prepared statement.
