### ISSUE TITLE
kafka inputbinding Infinite loop due to  none topics

### ISSUE THREAD

**Issue by ls-2018** [dapr/components-contrib#1399]
## Expected Behavior
The CPU can be maintained at a lower level
## Actual Behavior
1. Worry about allocating too many objects, resulting in too much GC pressure
2. The CPU is overloaded due to an infinite loop. If it is a K8S environment with limited resources, it is easy to OOM

## What version ?
1.5.0

## Steps to Reproduce the Problem
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: myevent
  namespace: default
spec:
  type: bindings.kafka
  version: v1
  metadata:
  - name: brokers
    value: localhost:9092
  - name: publishTopic
    value: topic1
  - name: consumerGroup
    value: app01
  - name: publishTopic
    value: topic-a
  - name: initialOffset
    value: "oldest"
  - name: authRequired
    value: "false"
  - name: maxMessageBytes
    value: 10240000
```
 Since there is no Topics field
bindings/kafka/kafka.go
```
		for {
			if err = client.Consume(ctx, k.topics, &c); err != nil {
				k.logger.Errorf("error from c: %s", err)
			} 
			if ctx.Err() != nil {
				return
			}
			c.ready = make(chan bool)
		}
```

RELEASE NOTE:

![image](https://user-images.githubusercontent.com/38821215/147640637-b484335d-54d5-46f7-a3a4-6ffa13206b52.png)

![image](https://user-images.githubusercontent.com/38821215/147640374-ec948590-00be-4683-a30d-1fd9d1298ac2.png)

![image](https://user-images.githubusercontent.com/38821215/147640359-39558673-dd69-4688-83f4-0cb270df4236.png)
