### ISSUE TITLE
Support Azure SignalR output binding

### ISSUE THREAD

**Issue by fbeltrao** [dapr/components-contrib#147]
Add output binding for Azure SignalR hubs, enabling scenarios where user notifications can be sent directly from Dapr.

Binding definition:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: signalr_out
spec:
  type: bindings.azure.signalr
  metadata:
  - name: connectionString
    value: Endpoint=https://<your-azure-signalr>.service.signalr.net;AccessKey=<your-access-key>;Version=1.0;
```

Calling from code:
```javascript
const daprPort = process.env.DAPR_HTTP_PORT || 3500;
const bindingUrl = `http://localhost:${daprPort}/v1.0/bindings`;
fetch(`${bindingUrl}/signalr_out`, {
    method: 'POST',
    body: JSON.stringify({
        data: {
            Target: "newMessage",
            Arguments: [
                {
                    sender: "dapr",
                    text: "notification from dapr"
                }]
        },
        metadata: {
            hub: "chat"
        }
    }),
    headers: {
        "Content-Type": "application/json"
    }
})
...
```
