### ISSUE TITLE
Postgres State Store: `cannot convert to pguint32` error when updating with ETag

### ISSUE THREAD

**Issue by pkedy** [dapr/components-contrib#1497]
## Expected Behavior

I should be able to update a key using ETag.

## Actual Behavior

A conversion error is returned...

```
cannot convert 956 to pguint32
```

where `956` is the ETag value.

## Steps to Reproduce the Problem

Calling `Set` on an existing item with an ETag should reproduce this.

I discovered this by using the Postgres state store as my Actor state store (config below) and invoking CreateReminder. The first call works, but successive calls fail (and block the actor due to retry code in the actor system).

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: host=XXX user=XXX password=XXX dbname=XXX port=5432 sslmode=disable
  - name: actorStateStore
    value: 'true'
```

## Release Note

RELEASE NOTE: **FIX** Setting a value using ETag for the Postgres state store
