### ISSUE TITLE
How to trigger my app by a self-developed binding

### ISSUE THREAD

**Issue by JieDing** [dapr/components-contrib#1590]
## Ask your question here
Hi folks - I'm new here. I've just tried to trigger my app with a Kafka binding.
Now I've a question about how to create a new binding and trigger my app with it.
I mean what I really want is to develop a binding and test it locally. Is there anyway to do that?
Like, I can implement interfaces the input binding requires, but how can I use it locally once I finished my codes.

I specify a binding.yaml like this when I use the Kafka binding
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: checkout
spec:
  type: bindings.kafka
  version: v1
  metadata:
  # Kafka broker connection setting
  - name: brokers
    value: localhost:9092
  # consumer configuration: topic and consumer group
  - name: topics
    value: sample
  - name: consumerGroup
    value: group1
  # publisher configuration: topic
  - name: publishTopic
    value: sample
  - name: authRequired
    value: "false"
```
How can I do it for a local self-developed binding implementation?

Thx a lot
