### ISSUE TITLE
jetstream server error:  processPub Parse Error

### ISSUE THREAD

**Issue by calvin2021y** [dapr/components-contrib#1655]
## Expected Behavior

expect nats work with dapr pubsub

## Actual Behavior

from the nats logs when dapr start:
```sh
processPub Parse Error: '$JS.API.CONSUMER.INFO.app.auth durable _INBOX.m9HDfvnkPYlwn7BOptt3tm.Z9dDtD9k 0'
```

## Steps to Reproduce the Problem

try with dapr jetstream demo

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.jetstream
  version: v1
  metadata:
  - name: natsURL
    value: "nats://nats:4222"
  - name: name
    value: "auth connection"
  - name: durableName
    value: "auth durable" 
  - name: queueGroupName
    value: "auth queue group"
  - name: startSequence
    value: 1
  - name: startTime # in Unix format
    value: 1630349391
  - name: deliverAll
    value: false
  - name: flowControl
    value: false
```

```go
package main

import (
	"context"
	"log"
	"net/http"

	"github.com/dapr/go-sdk/service/common"
	daprd "github.com/dapr/go-sdk/service/grpc"
)

//code
var sub = &common.Subscription{
	PubsubName: "pubsub",
	Topic:      "auth",
	Route:      "/auth",
}

func main() {
	s, err := daprd.NewService(":5001")
	if err != nil {
		log.Fatalf("error adding topic subscription: %v", err)
	}
	//Subscribe to a topic
	if err = s.AddTopicEventHandler(sub, eventHandler); err != nil {
		log.Fatalf("error adding topic subscription: %v", err)
	}
	if err := s.Start(); err != nil && err != http.ErrServerClosed {
		log.Fatalf("error listenning: %v", err)
	}
}

func eventHandler(ctx context.Context, e *common.TopicEvent) (retry bool, err error) {
	log.Printf("Subscriber received: %s", e.Data)
	return false, nil
}
```

publish is work, subscription send message nats can not understood.

the dapr logs:

```sh
failed to subscribe to topic auth: context deadline exceeded
```

nats ` Version:  2.7.4`

dapr 1.7, go-sdk 1.4
