### ISSUE TITLE
[pubsub-pulasr] "server error: ConsumerBusy: Subscription is of different type

### ISSUE THREAD

**Issue by saber-wang** [dapr/components-contrib#1656]
## Expected Behavior
Subscription succeeded

## Actual Behavior

Subscription failed and started

## Steps to Reproduce the Problem

Upgrade from 1.6.0 to 1.7.0 and restart the service

```
time="2022-04-10T05:35:49Z" level=error msg="[Failed to create consumer]" consumerID=7 error="server error: ConsumerBusy: Subscription is of different type" name=ygedd subscription=demo topic="persistent://public/production/testEvent"
```
This error disappears after restarting the service again

**Comment by shubham1172** [comment]
Can you please share more details on the configuration you are using and how to reproduce this? Does the problem mitigate after restarting the service until the next restart?

**Comment by saber-wang** [comment]
@shubham1172  It can be solved by restarting once

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: mcrp-dev
spec:
  type: pubsub.pulsar
  version: v1
  metadata:
  - name: host
    value: ip:port
  - name: enableTLS
    value: "false"
  - name: namespace
    value: "production"
```
