### ISSUE TITLE
[pubsub-pulsar]disableBatching Invalid setting

### ISSUE THREAD

**Issue by saber-wang** [dapr/components-contrib#1682]
## Expected Behavior

disable batch

## Actual Behavior

disableBatching Invalid setting

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.pulsar
  version: v1
  metadata:
  - name: host
    value: host
  - name: enableTLS
    value: "false"
  - name: backOffMaxRetries
    value: "50"
  - name: disableBatching
    value: "true"
```

Exceptions will still be thrown：
```
time="2022-04-15T01:52:07Z" level=error msg="[unable to add message to batch]" producerID=8 producer_name=pulsar-cluster-zk-3-2988 properties="map[]" size=270636 topic="persistent://public/default/testEvent"
time="2022-04-15T01:52:07.670125177Z" level=debug msg="rpc error: code = Internal desc = error when publish to topic testEvent in pubsub pubsub: message add to batch failed: AddToBatchFailed" app_id=test instance=test-1.2.65-5f89f79776-bkpxf scope=dapr.runtime.grpc.api type=log ver=1.7.0
```

**Comment by shubham1172** [comment]
Hello @saber-wang, I am not able to reproduce this with the latest Dapr version. Here is my configuration file:
```yml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pulsar-pubsub
  namespace: default
spec:
  type: pubsub.pulsar
  version: v1
  metadata:
  - name: host
    value: "localhost:6650"
  - name: disableBatching
    value: "true"
```

I was able to publish and listen for data, without running into the mentioned error. 
1. What version are you on?
2. Can you please share a minimum reproducible example? 
3. Also, can you share the complete Dapr logs?
