### ISSUE TITLE
How to use Cosmos DB when container name is only known at runtime?

### ISSUE THREAD

**Issue by remojansen** [dapr/components-contrib#1900]
I'm working on a SaaS solution, and the users are allowed to create workspaces. Each workspace uses several CosmosDB containers pre-fixed with the workspace ID:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: invitations-store
  namespace: default
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    value: "https://xxxxxx.documents.azure.com:443/"
  - name: masterKey
    secretKeyRef:
      name: "cosmosMasterKey"
  - name: database
    value: "xxxxxx"
  - name: collection
    value: "<WORKSPACE-ID>.environments" <-- HERE
  - name: partitionKey
    value: "id"
```

Is there a way to connect to a container without declaring a component? Can the component be declared at runtime?
