### ISSUE TITLE
Apache Cassandra Certification tests

### ISSUE THREAD

**Issue by addjuarez** [dapr/components-contrib#1915]
## Describe the proposal

It seems conformance tests have already been setup for cassandra. 
https://github.com/dapr/components-contrib/blob/master/tests/conformance/common.go#L429
Now we need to create certification tests for cassandra to graduate component to stable.
Currently cassandra supports CRUD operations and TTL.
https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-cassandra/

**Comment by artursouza** [comment]
LGTM

**Comment by berndverst** [comment]
The CRUD operation are covered by conformance tests and should **not** be part of certification tests.

You also need tests covering the metadata options:

```yaml
  - name: consistency
    value: <REPLACE-WITH-CONSISTENCY> # Optional. default: "All"
  - name: table
    value: <REPLACE-WITH-TABLE> # Optional. default: "items"
  - name: keyspace
    value: <REPLACE-WITH-KEYSPACE> # Optional. default: "dapr"
  - name: protoVersion
    value: <REPLACE-WITH-PROTO-VERSION> # Optional. default: "4"
  - name: replicationFactor
    value: <REPLACE-WITH-REPLICATION-FACTOR> #  Optional. default: "1"
```
