### ISSUE TITLE
Add Aerospike as a state store

### ISSUE THREAD

**Issue by abhirockzz** [dapr/components-contrib#195]
## Describe the proposal

Add support for [Aerospike](https://www.aerospike.com/) - a NoSQL data store

**Comment by abhirockzz** [comment]
Sample configuration
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: aerospike
spec:
  type: state.aerospike
  metadata:
    - name: hosts
      value: "localhost:3000"
    - name: namespace
      value: "test"
    - name: set
      value: "set1"
```
