### ISSUE TITLE
Crashes and errors with statestore and CosmosDB.

### ISSUE THREAD

**Issue by alexandrejulien** [dapr/components-contrib#1970]
## Expected Behavior

Statestore with cosmosdb occurs crashes on dapr sidecar with Dapr 1.7.4
Using .NET App with Dapr Client for ASP.NET SDK with .Net 6 runtime.

This my dapr component :
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: shared-statestore
  namespace: azure
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    value: https://XXXXXXXXXXXXXXX.azure.com:443/
  - name: masterKey
    value: XXXXXXXXXX
  - name: database
    value: rec-statestores
  - name: collection
    value: shared-state
  - name: keyPrefix
    value: none
```

## Actual Behavior

The dapr process crash probably when calling StateStore on CosmosDb.
No problem on Redis statestore.

2022-08-10T08:38:11.094454210Z goroutine 6630 [running]:
2022-08-10T08:38:11.094459310Z github.com/dapr/components-contrib/state/azure/cosmosdb.(StateStore).Get(0xc000b74280, 0xc000e7cab0)
2022-08-10T08:38:11.094465710Z     /home/runner/go/pkg/mod/github.com/dapr/c**@v1.7.1/state/azure/cosmosdb/cosmosdb.go:241 +0x61a
2022-08-10T08:38:11.094471010Z github.com/dapr/dapr/pkg/grpc.(api).GetState.func1({0x398e6c0, 0x4510801})
2022-08-10T08:38:11.106194011Z ℹ️
2022-08-10T08:38:11.106214211Z terminated signal received: shutting down
2022-08-10T08:38:11.106280411Z ❌  The daprd process exited with error code: exit status 2
2022-08-10T08:38:11.106290511Z ❌  Error exiting Dapr: exit status 2
2022-08-10T08:38:11.107867311Z ✅  Exited App successfully

## Steps to Reproduce the Problem

Using Statestore with CosmosDb with prefix and without prefix (2 dapr components)
