### ISSUE TITLE
Proposal: Enhanced Semantic Conventions.

### ISSUE THREAD

**Issue by 1046102779** [dapr/components-contrib#1977]
## Semantic convention

I just encountered a headache when implementing the `secretstores.tencent.ssm` standardized component. How do I name fields like `secretid`, `secretkey`, `token`, `region`, etc. 

I see that almost every component currently uses the go-sdk of each cloud product, and directly marshal & unmarshal metadata to target sdk protocol of the target cloud product. As a result, the MicroLogic server often has to look at the field adaptation when using it, which is really unfriendly.  Such as(secretstores):

|component(**secretstores**)|secretid|secretkey|region|token|versionid|
|---|---|---|---|---|---|
|alicloud.parameterstore|accessKeyId|accessKeySecret|regionId|securityToken|version_id|
|azure.keyvault|-|-|-|-|version_id|
|hashicorp.vault|-|-|-|vaultToken|version_id|
|aws.parameterstore|accessKey|secretKey|region|sessionToken|version_id|
|aws.secretmanager|accessKey|secretKey|region|sessionToken|version_id|
|gcp.secretmanager|private_key_id|private_key|-|-|version_id|
|huaweicloud.csms|accessKey|secretAccessKey|region|-|version_id|

So if MicroLogic server uses `alicloud.parameterstore`:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: alisecretstore
spec:
  type: secretstores.alicloud.parameterstore
  version: v1
  metadata: 
  - name: accessKeyId
    value: xxx
  - name:  accessKeySecret
   value: xxx
  - name: regionId
   value: xxx
```

another secretstores component `huaweicloud.csms`:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: huaweisecretstore
spec:
  type: secretstores.huaweicloud.csms
  version: v1
  metadata: 
  - name: accessKey
    value: xxx
  - name:  secretAccessKey
   value: xxx
  - name: region
   value: xxx
```

The same problem exists for the metadata data field carrying in the non-initialization phase, so I think semantic convention is very important. We can standardize the standard or general standardization ability and make the greatest common divisor specification of the field.

The same goes for other standardized components.
