### ISSUE TITLE
Support for Priority Queues in RabbitMQ with pubsub

### ISSUE THREAD

**Issue by kayvonkhosrowpour** [dapr/components-contrib#2029]
## Describe the feature
RabbitMQ supports the ability to create [priority queues](https://live.rabbitmq.com/priority.html) through the `x-max-priority` property. Although dapr supports priority queues through the `maxPriority` attribute in the [binding spec](https://docs.dapr.io/reference/components-reference/supported-bindings/rabbitmq/), there is no support in pubsub.

This feature request is to support the ability to create priority queues in the rabbitMQ pubsub component definition. Ideally, we would be able to create priority queues off a topic by name or pattern. For example, I have an exchange called "primary", and I have queues off the exchange called A, B, C. I only need C to be a priority queue, so I should be able to designate priority-C as having priority, whereas priority-A and priority-B do not need to have priority.

Please let me know what additional information would be helpful.

## Potential
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: priority
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  # ...
  # standard config
  # ...
  - name: maxPriorities
     value:
         C: 5 # this specifies the max priority for queue C off exchange topic "priority"
```

## Release Note
RELEASE NOTE: **ADD** New feature in Dapr - RabbitMQ priority queue support in pubsub component

**Comment by kayvonkhosrowpour** [comment]
@yaron2  @berndverst @artursouza -- Any chance we can support this? Issue will be closed soon

**Comment by a2bondar** [comment]
This would be excellent for us as well. What is needed to get this added to release schedule?

**Comment by Taction** [comment]
Better add this config in the metadata of `Subscription` config, such as:
```
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: order
spec:
  topic: orders
  route: /checkout
  pubsubname: pubsub
  metadata:
  - name: maxPriorities
     value: "10"
```
and handle this metadata in the rabbitmq pubsub component. Also, add a metadata specifying priority per message level.
@kayvonkhosrowpour  are you interested in submitting ap pr for this?
