### ISSUE TITLE
Metadata serialization for duration based values do not work anymore

### ISSUE THREAD

**Issue by akkie** [dapr/components-contrib#2050]
## Expected Behavior

Previously it was possible to define a duration based value as string in the format: 45s

An example is the Zeebe worker binding:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-component-name
spec:
  type: bindings.zeebe.jobworker
  version: v1
  metadata:
    - name: workerTimeout
      value: 30s
    - name: requestTimeout
      value: 15s
```
https://docs.dapr.io/reference/components-reference/supported-bindings/zeebe-jobworker/

The implementation is based on: https://github.com/dapr/components-contrib/blob/master/metadata/duration.go#L25

There were no changes to this code. There were some changes in the Zeebe worker binding last month, but not for duration based values. So I'm not sure where the issue comes from.

## Actual Behavior

With the lates master it's not possible anymore to start a dapr based application if there is a string defined for a duration based value. The following error will be shown:

```
FATA[0005] process component my-component-name error: [INIT_COMPONENT_FAILURE]: initialization error occurred for my-component-name (bindings.zeebe.jobworker/v1): 2 error(s) decoding:

* 'RequestTimeout' expected a map, got 'string'
* 'WorkerTimeout' expected a map, got 'string'  app_id=my-app instance=tron.local scope=dapr.runtime type=log ver=edge
❌  The daprd process exited with error code: exit status 1
```

## Steps to Reproduce the Problem

```
mkdir dapr-duration-issue
mkdir dapr-duration-issue/components
cat > dapr-duration-issue/components/my-component-name.yaml <<EOL
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-component-name
spec:
  type: bindings.zeebe.jobworker
  version: v1
  metadata:
    - name: gatewayKeepAlive
      value: 45s
    - name: workerTimeout
      value: 30s
    - name: requestTimeout
      value: 15s
EOL
dapr run --app-id my-app --components-path ./dapr-duration-issue/components

```
## Release Note

RELEASE NOTE: **FIX** Duration based metadata serialization
