### ISSUE TITLE
[Binding] Azure Digital Twin support

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/components-contrib#2053]
## Describe the feature

I would love support for Azure Digital Twin. It's one of the most difficult components to work with from Azure, but enables interesting use cases in the IoT world.

Could be as easy as creating a component description as follows:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: binding-digital-twin
spec:
  type: bindings.azure.digitaltwin
  version: v1
  metadata:
  - name: hostName
    value: https://******.api.neu.digitaltwins.azure.com:443/
  - name: model
    value: dtmi:com:your_org:ModelName;1
```

So that we can invoke a binding that adds data to a specified model

## Release Note

RELEASE NOTE: 
**ADD** Azure Digital Twin support
