### ISSUE TITLE
[PubSub Jetstream] Changing deliver policy on a durable consumer throws an error

### ISSUE THREAD

**Issue by NickLarsenNZ** [dapr/components-contrib#2162]
I'm migrating applications to new Dapr Components (Moving from from Ephemeral to Durable Consumers). As part of that, my initial deployment sets the `startTime` on the new durable consumers so we don't process all messages from the beginning.

## Expected Behavior

When removing the `startTime` configuration from the `Component` configuration, the Consumer's deliver policy should be updated accordingly.

Eg: `nats con info <stream> <consumer> | grep "Deliver Policy"` should change from:

```
      Deliver Policy: Since 2022-10-07 09:29:28 +0000 UTC
```

to

```
      Deliver Policy: Last
```

## Actual Behavior

1. When the manifest changes (to remove the `startTime` configuration, Dapr doesn't notice it, so nothing changes (all still works normal however).
2. When Dapr is restarted, the consumers are deleted from NATS, and an error is thrown:
   ```
   time="2022-10-07T10:35:10.241913173Z" level=error msg="failed to subscribe to topic my.topic: configuration requests deliver policy to be 1, but consumer's value is 4" app_id=my-app-api instance=my-app-api-65d7d9488b-jw7pr scope=dapr.runtime type=log ver=1.8.4
   ```
3. Dapr needs to be restarted a second time, and finally it all comes back with the expected Consumer settings (Deliver Policy: Last).

> **Note**: While point 1 might seem reasonable, it gives a false assumption that everything is fine, and defers the failure which requires manual intervention. I believe Dapr should be failing, causing it to restart automatically (in my case).
> According to the docs, `spec.ignoreErrors` defaults to `false`, so the failure shouldn't be permitted, IMO.

## Steps to Reproduce the Problem

I'm running this in Kubernetes with the Dapr Operator. I assume the same would happen in standalone mode.

1. Create a Jetstream PubSub Component with the `startTime` set.
   ```yml
   apiVersion: dapr.io/v1alpha1
   kind: Component
   metadata:
     name: my-pubsub
   spec:
     type: pubsub.jetstream
     version: v1
     metadata:
     - name: natsURL
       value: "tls://nats"
   
     # Create a Durable Consumer where NATS will store a pointer to the last ACKed message
     # This prevents us from missing messages if the service is down. It will resume from where it left off
     - name: durableName
       value: my-pubsub
   
     # Probably not needed in this example, but I'll leave it here as it is how I had configured it.
     - name: queueGroupName
       value: my-pubsub

     # Only process messages from this point onward
     - name: startTime
       value: 1665141361 # date -d '2 minutes ago' +%s
   ```
2. Ensure Dapr is subscibing via that consumer (ie: no errors when it starts)
   - You can also check via `nats con info <STREAM> my-pubsub`. The `Deliver Policy: Since 
4. Remove the `startTime` configuration, ie:
   ```yml
     # # Only process messages from this point onward
     # - name: startTime
     #   value: 1665141361 # date -d '2 minutes ago' +%s
   ```
5. Restart Dapr
6. Notice the Consumer is deleted when you run `nats con list <STREAM>`
7. See the error thrown in Dapr:
   ```
   failed to subscribe to topic my.topic: configuration requests deliver policy to be 1, but consumer's value is 4
   ```
8. Restart Dapr, and the Consumer will be created correctly, with `Deliver Policy: Last`.

## Release Note

RELEASE NOTE:
