### ISSUE TITLE
Inconsistent retry behavior between pubsub providers

### ISSUE THREAD

**Issue by danielgerlag** [dapr/components-contrib#2204]
## Expected Behavior

If I have an app that subscribes to a topic and returns a "RETRY" status, I will not get any future messages until that particular message is processed, as I need to process in sequence.

## Actual Behavior

It works as expected when using Azure Event Hubs or Kafka, but with Redis Streams, I continue to get the messages in the stream after the RETRY message.

**Comment by danielgerlag** [comment]
Ping

**Comment by danielgerlag** [comment]
@berndverst

**Comment by ItalyPaleAle** [comment]
Hi @danielgerlag last week was a holiday week in the US and our team was mostly not at work.

Can you share your component YAML files and any information that can help us reproduce the issue?

**Comment by danielgerlag** [comment]
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "localhost:9092"
  - name: authType
    value: "none"
```

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rg-pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: rg-redis:6379
  - name: concurrency
    value: 1
  - name: maxLenApprox
    value: 10000
```
