### ISSUE TITLE
Twitter Binding: Add support for Twitter API v2

### ISSUE THREAD

**Issue by cmendible** [dapr/components-contrib#2283]
Twitter launched their API v2 which is now the default for Twitter applications. V1 applications can no longer be created.

The Twitter Binding should add support for the Twitter v2 API.

Perhaps the component should expose a property to specify the Twitter API version to use.

## Additional info

Binding starts with a v2 Twitter app but tweets don't flow into the stream.

The problem is caused by [go-twitter](https://github.com/dghubble/go-twitter) dependency:

- Project is now archived
- It was written for Twitter API v1 
- It does not work with Twitter API v2

## Steps to Reproduce the Problem

Create a Twitter API v2 app and run the streaming sample provided here: https://github.com/dghubble/go-twitter/tree/main/examples

Tweets will not flow.

**Comment by berndverst** [comment]
https://developer.twitter.com/en/docs/twitter-api/tools-and-libraries/v2

These are our choices for SDKs to use in the implementation:
[ctw](https://github.com/0dayfall/ctw) a library for the Twitter API
[go-twitter](https://github.com/g8rswimmer/go-twitter) a Go library for Twitter v2 API integration.
[gotwi](https://github.com/michimani/gotwi) a library for the Twitter API v2 in Go
[gotwtr](https://github.com/sivchari/gotwtr) a library for the Twitter API
[twitter-stream](https://github.com/Fallenstedt/twitter-stream) a Go wrapper for Twitter's V2 Filtered Stream API
[twitter](https://github.com/creachadair/twitter) a Go client for the Twitter API

**Comment by berndverst** [comment]
With 178 stars right now this SDK has the most stars: https://github.com/g8rswimmer/go-twitter

**Comment by berndverst** [comment]
The current component spec is
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: <NAME>
spec:
  type: bindings.twitter
  version: v1
  metadata:
  - name: consumerKey
    value: "****" # twitter api consumer key, required
  - name: consumerSecret
    value: "****" # twitter api consumer secret, required
  - name: accessToken
    value: "****" # twitter api access token, required
  - name: accessSecret
    value: "****" # twitter api access secret, required
```

We could create a new v2 version of this component which could map to the Twitter v2 API, instead of creating a metadata field for the Twitter API version. This way we can separate the existing binding code with the old SDK and the code using the new SDK.
