### ISSUE TITLE
GCP Pub/sub HOW TO

### ISSUE THREAD

**Issue by krab-skunk** [dapr/components-contrib#2341]
Hello @berndverst @ItalyPaleAle @yaron2  ;)

I noticed you worked on the GCP pub/sub feature so i would have liked to ask you a little help please ;) 

I'm using dapr with redis pubsub for a while now and i wanted to use GCP pub/sub in order to have easy interface communications between GCP service and some of my pods on k8s , so i did as follow:

Create a pubsub binding for k8s such as: 
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: gcp-pubsub
spec:
  type: pubsub.gcp.pubsub
  version: v1
  metadata:
  - name: type
    value: service_account
  - name: projectId
    value: super-project-gcp-dev 
  - name: identityProjectId
    value: "super-project-gcp-dev" 
  - name: privateKeyId
    value: "8..................................." 
  - name: clientEmail
    value: "dapr-pubsub@super-project-gcp-dev.iam.gserviceaccount.com" 
  - name: clientId
    value: 11...............................
  - name: authUri
    value: https://accounts.google.com/o/oauth2/auth
  - name: tokenUri
    value: https://oauth2.googleapis.com/token
  - name: authProviderX509CertUrl
    value: https://www.googleapis.com/oauth2/v1/certs
  - name: clientX509CertUrl
    value: "https://www.googleapis.com/robot/v1/metadata/x509/dapr-pubsub%40super-project-gcp-dev.iam.gserviceaccount.com"
  - name: privateKey
    value: "-----BEGIN PRIVATE KEY-----\nMIIEvQI........mvRfbs=\n-----END PRIVATE KEY-----\n"
  - name: disableEntityManagement
    value: "false"
  - name: enableMessageOrdering
    value: "false"
  - name: maxReconnectionAttempts 
    value: 30
  - name: connectionRecoveryInSec 
    value: 2
```

I made a little quick python app for a simple test:
```
@gcppubsub_client.route('/dapr/subscribe', methods=['GET'])
def subscribe():
    subscriptions = [{'pubsubname': 'gcp-pubsub', 'topic': 'gcppubsubtopic', 'route': "pubsubroute"}]
    return jsonify(subscriptions)

@gcppubsub_client.route('/pubsubroute', methods=["POST"])
def scanning():
    print("event triggered", flush=True)
    print(request.json, flush=True)
    return json.dumps({'success':True}), 200, {'ContentType':'application/json'}
```

The deployment file look as follow:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcppusub-client
  labels:
    app: gcppusub-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcppusub-client
  template:
    metadata:
      labels:
        app: gcppusub-client2
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "gcppusub-client"
        dapr.io/app-port: "9000"
        dapr.io/http-max-request-size: "20"
    spec:
      containers:
      - name: gcppusub-client
        image: gcr.io/super-project-gcp-dev/gcppubsub-client-dev:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
```

When i deploy this app in my k8s cluster, that automatically create a GCP pubsub with topicID `gcppubsubtopic` and subscription ID `gcppusub-client-gcppubsubtopic`

To try, i went to GCP console >> Topic, chose `gcppubsubtopic` Topic, and clicked **Public Message**

I Just filled in the message Body with `Hello World`, hoping my app would receive it and display it, but i never manage to
receive anything, and i couldn't find a tutorial showing end to end scenario, so that's why i'm writing you hoping you could help me understand what am i missing :)

Thank you so much in advance 

Dapr version 1.8.4

PS; `super-project-gcp-dev` is a random name for the sake of this post ;)
