### ISSUE TITLE
MongoDB as an actor state store does not work

### ISSUE THREAD

**Issue by danielgerlag** [dapr/components-contrib#2351]
If I used Redis as my actor state store, it works fine, but if I switch to Mongo, then as soon as an actor tries to persist state, the app crashes and I see this error:
```
Error: {"errorCode":"ERR_ACTOR_STATE_TRANSACTION_SAVE","message":"error saving actor transaction state: error during transaction, aborting the transaction: (IllegalOperation) Transaction numbers are only allowed on a replica set member or mongos"}
```

Is there a special way you need to configure Mongo for actors that is not documented?

**Comment by jaceks2106** [comment]
Hello,

Any update on this? Problem still occurs.

**Comment by ItalyPaleAle** [comment]
How are you spinning up MongoDB?

**Comment by jaceks2106** [comment]
> How are you spinning up MongoDB?

FYI, I am using dapr with Tye.

Tye definition:

```yaml
name: example-app
extensions:
- name: dapr
  components-path: ./dapr/components

services:

  - name: example-db
    image: mongo
    bindings:
      - port: 27017
    volumes:
      - name: example-db
        target: /data/db
      - source: ./env_files/mongodb_runfiles
        target: /docker-entrypoint-initdb.d
    env_file:
      - ./env_files/mongodb.env

```

./dapr/components
``` yaml
apiVersion: dapr.io/v1alpha1
kind: Component

metadata:
  name: example-statestore

spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    value: "localhost:27017"
  - name: username
    value: "example"
  - name: password
    value: "example_password"
  - name: databaseName
    value: "example"
  - name: params
    value: "?authSource=example"
  - name: operationTimeout
    value: "60s"
  - name: readConcern
    value: "local"
  - name: writeConcern
    value: 0

  - name: actorStateStore
    value: "true"

scopes:
- example

```

./env_files/mongodb.env
```
MONGO_INITDB_ROOT_USERNAME=admin
MONGO_INITDB_ROOT_PASSWORD=password
MONGO_INITDB_DATABASE=admin
```

./env_files/mongodb_runfiles - mongo-init.js

```js
const dbName = 'example'
const collection = 'daprCollection'

db = db.getSiblingDB(dbName)

db.createUser(
        {
            user: "example",
            pwd: "example_password",
            roles: [
                {
                    role: "readWrite",
                    db: "example"
                }
            ]
        }
);

db.createCollection(collection);
```
