### ISSUE TITLE
how to rewrite Component properties in RocketMq pubsub

### ISSUE THREAD

**Issue by naah69** [dapr/components-contrib#2370]
We want create a public rocketmq pubsub component in k8s crd without `producerGroup` and `consumerGroup`.

And we will set both of them on annotations or envirement vairables of depolyment.yaml.

is the way available？

**Comment by naah69** [comment]
@jinjianfeng-chn 
now we have to add many rocketmq crd to implement that every service set different consumerGroup and producerGroup.
I am not good at Golang
Can u help me to add the feature that envirement vairable can rewrite consumerGroup and producerGroup?

**Comment by berndverst** [comment]
@naah69 I will not accept the PR you opened. Loading random environment variables from within the component is now the correct pattern.

You can change your PR such that when no consumer group is specified it uses the default value that is autogenerated (which is the same as the app ID). This metadata key will be `consumerID`.

Another option is something like this:
Instead, what you can do is something with this.
https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-namespace/#with-namespace-consumer-groups

**Comment by berndverst** [comment]
I have a better idea for you @naah69:

Configure the environment variable secret store.
https://docs.dapr.io/reference/components-reference/supported-secret-stores/envvar-secret-store/

Then configure your Dapr component,
and for the consumerGroup you would do something like in your component:

```
 metadata:

// other component metadata here

    - name: consumerGroup //
      secretKeyRef:
        name: MYCONSUMERGROUPENVVAR // can be anything you want
        key: MYCONSUMERGROUPENVVAR
    - name: producerGroup //
      secretKeyRef:
        name: MYPRODUCERGROUPENVVAR // can be anything you want
        key: MYPRODUCERGROUPENVVAR
auth:
  secretStore: envvar-secret-store
```

This assumed you have the following secret store also loaded:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: envvar-secret-store
  namespace: default
spec:
  type: secretstores.local.env
  version: v1
  metadata:
```
