### ISSUE TITLE
Add Azure Event Hubs as a PubSub component

### ISSUE THREAD

**Issue by abhirockzz** [dapr/components-contrib#241]
## Describe the proposal

Add Azure Event Hubs as a Dapr PubSub component

**Comment by abhirockzz** [comment]
To use Azure Event Hubs as a PubSub component:

- Create Azure Event Hubs namespace and an Event Hub
- Create Azure Blob Storage account and container
- Use the following component config

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: <enter a name e.g. eventhub-pubsub>
spec:
  type: pubsub.azure.eventhubs
  metadata:
    - name: connectionString
      value: "Endpoint=sb://<enter namespace>.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=<enter key>;EntityPath=<enter event hub name>"
    - name: storageAccountName
      value: <enter storageAccountName>
    - name: storageAccountKey
      value: <enter storageAccountKey>
    - name: storageContainerName
      value: <enter storageContainerName>
```
