### ISSUE TITLE
Add options for token authentication and automatic JWT tokens for HTTP binding

### ISSUE THREAD

**Issue by yaron2** [dapr/components-contrib#2468]
Support for the following:

```yaml
kind: Component
metadata:
  name: mybinding
spec:
  type: bindings.http
  version: v1
  metadata:
    - name: url
      value: http://something.com/
# Fixed security token
    - name: securityToken
      secretKeyRef:
        name: securitytoken
    - name: securityHeader
      value: x-token
# JWT header
    - name: jwtIssuer
      value: http://ibm.jwtsissuer.com/v1/issue
    - name: jwtIssuerToken
      secretKeyRef:
        name: issuertoken
    - name: jwtIssuerHeader
      value: x-token
```
