### ISSUE TITLE
Proposal: TTL in Local Storage binding 

### ISSUE THREAD

**Issue by federicocodo** [dapr/components-contrib#2502]
## Describe the proposal
After working with the [Local Storage binding](https://docs.dapr.io/reference/components-reference/supported-bindings/localstorage/) for my service application, i found a potential proposal:
add in the yaml component a metadata field, time to live, for the files (as other components like redis state store)

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: <NAME>
spec:
  type: bindings.localstorage
  version: v1
  metadata:
  - name: rootPath
    value: <string>
  - name: ttl
    value: <int> # Optional
```

Otherwise, taking into account the fact that certain files must not be deleted, it could be done so that (as for redis) when a file is created, the ttl can be added in the metadata field.
The ttl could be in seconds as done previously.
