### ISSUE TITLE
Oauth2 Not Adding Token to Request Header

### ISSUE THREAD

**Issue by drewby** [dapr/components-contrib#2615]
## Expected Behavior

Oauth2 Middleware component for Authorization Code Grant flow is supposed to add the Bearer token to a request header after authentication.  This header is then sent along with the request to the app for validation and claims lookup. This works correctly in v1.9.

## Actual Behavior

In v1.10, the Oauth2 Middleware component is adding the Bearer token to the Response headers instead of the Request headers. The token is going back to the client application which is not expected.

## Steps to Reproduce the Problem

1. Simple controller to return headers (ASP.NET core / C#):

```csharp
var app = WebApplication.Create(args);

app.MapGet("/Headers", (HttpRequest request) =>
{
    var headers = request.Headers;
    return new Microsoft.AspNetCore.Mvc.ObjectResult(headers);    
});

app.Run();
```

2. Create component config

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: oauth2
spec:
  type: middleware.http.oauth2
  version: v1
  metadata:
  - name: clientId
    value: <clientId>
  - name: clientSecret
    value: <clientSecret>
  - name: scopes
    value: "api://appId/TodoList.Read, api://appId/TodoList.ReadWrite"
  - name: authURL
    value: "https://login.microsoftonline.com/tenantId/oauth2/v2.0/authorize"
  - name: tokenURL
    value: "https://login.microsoftonline.com/tentId/oauth2/v2.0/token"
  - name: redirectURL
    value: "http://localhost:8080/v1.0/invoke/test/method/Headers"
  - name: authHeaderName
    value: "Authorization" 
```

3. Configure middleware

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  namespace: nginx
  name: dapr-config
spec: 
  httpPipeline:
    handlers:
      - name: oauth2 
        type: middleware.http.oauth2
```

4.  Run dapr

```bash
dapr run --app-id test --config config.yaml --components-path ./components/ --app-port 5000 -H 8080 -- dotnet run --project ./src --urls http://localhost:5000
```

With daprd 1.9, we see the Bearer token header. In daprd 1.10, there is no Bearer token header.

## Release Note

RELEASE NOTE: **FIX** Oauth2 middleware adds Bearer token to request headers.
