### ISSUE TITLE
Nats Jetstream PubSub - cannot create a queue subscription for a consumer without a deliver group

### ISSUE THREAD

**Issue by benfu-verses** [dapr/components-contrib#2645]
After upgrading to Dapr 1.10, our previously working Jetstream pub/sub is broken. On Dapr startup the nats client complains that it cannot create a queue subscription for a consumer without a configured deliver group. My guess is after this change: https://github.com/dapr/components-contrib/commit/47a46673cda3a3523ef66a24a2b1a0ad67f2191d the Nats client library is always configured with a queue group but the `DeliverGroup` Jetstream parameter option is not exposed or configurable, thus resulting in the error here: https://github.com/nats-io/nats.go/blob/main/js.go#L1320

## Expected Behavior
Dapr sidecar should subscribe to Jetstream.

## Actual Behavior

Dapr sidecar fails to subscribe on startup:
```
time="2023-03-08T02:50:47.269284573Z" level=error msg="error occurred while beginning pubsub for topic blah.> on component pubsub-nats-jetstream: failed to subscribe to topic blah.>: cannot create a queue subscription for a consumer without a deliver group" app_id=app instance=app-745d98569-mm9dn scope=dapr.runtime type=log ver=1.10.2
```

## Steps to Reproduce the Problem

We have a simple Nats server deployed running on `2.9.14-alpine` with Jetstream enabled.

PubSub:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-nats-jetstream
spec:
  type: pubsub.jetstream
  version: v1
  metadata:
    - name: natsURL
      value: "nats://nats:4222"
    - name: name
      value: "dapr-pubsub"
```

Subscription:
```yaml
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: app-subscription
spec:
  topic: "blah.>"
  routes:
    default: /
  pubsubname: pubsub-nats-jetstream
scopes:
  - app
 ```
