### ISSUE TITLE
Bearer middleware fails with 404 when using Azure AD B2C

### ISSUE THREAD

**Issue by tophallen** [dapr/components-contrib#2718]
We are using Azure AD B2C for our authentication and we have been unable to get it to work, we get a 404 error, which seems like it is due to the issuer actually not being a valid url. From what I understand that is expected behavior for a B2C issuer url. Is this a limitation of the middleware component or a bug that it seems to rely on calling the issuer url?

## Expected Behavior

Should be able to start the service successfully, verify a token, and authorize the user on a request.

## Actual Behavior

The service fails to start because this error shows up in the dapr container logs:

```
failed to open http channel to app: error creating HTTP middleware middleware.http.bearer/: 404 Not Found: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
```

## Steps to Reproduce the Problem

Bearer component:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: bearer
spec:
  type: middleware.http.bearer
  version: v1
  metadata:
    - name: clientId
      value: {client id}
    - name: issuerURL
      value: https://{tenant name}.b2clogin.com/{tenant name}.onmicrosoft.com/v2.0/.well-known/openid-configuration?p={policy name}
```

I also tried this with the issuer url that is provided in the openid configuration: `https://{tenant name}.b2clogin.com/{tenant id}/v2.0/` which if you call the issuer endpoint in a browser you get this in the 404 response: `The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.`

Using the above component and including in the middleware configuration:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: http-pipeline
spec:
  mtls:
    enabled: true
  appHttpPipeline:
    handlers:
    - name: bearer
      type: middleware.http.bearer
```

This is all that is needed with any service to run into the same issue.

Deployment yaml annotations:

```yaml
template:
    metadata:
      labels:
        app: myapp
        kind: api
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "myapp-api"
        dapr.io/id: "myapp-api"
        dapr.io/app-port: "6003"
        dapr.io/app-protocol: "http"
        dapr.io/app-ssl: "false"
        dapr.io/enable-api-logging: "true"
        dapr.io/api-token-secret: "dapr-api-token"
        dapr.io/app-token-secret: "app-api-token"
        dapr.io/config: "http-pipeline"
```

I have not had issues with other functionalities and components, including other authorization methods and OPA policies, but I cannot get this component to work with Azure B2C.

The specs:

- Windows 10 22H2
- docker desktop 4.17.0 (Engine 20.10.23) using WSL2
- kubernetes 1.25.4
- dapr version 1.10.2

## Release Note

RELEASE NOTE:
