### ISSUE TITLE
All sidecars failed since new binding installed

### ISSUE THREAD

**Issue by steve-heslouin** [dapr/components-contrib#2721]
## In what area(s)?

> /area runtime

/area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.1.x

## Expected Behavior

I created an SQS Bindings as follow :

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sqs-bindings
spec:
  type: bindings.aws.sqs
  version: v1
  metadata:
  - name: queueName
    value: myqueue
  - name: region
    value: us-east-1
```

And now , all the dapr side car that are attached to a pod having a service account pointing to a Iam Role Service Account (IRSA)
are failing with this error:
```
time="2023-03-29T17:09:40.856142471Z" level=fatal msg="process component sqs-bindings error: [INIT_COMPONENT_FAILURE]: initialization error occurred for sqs-bindings (bindings.aws.sqs/v1): AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist or you do not have access to it.\n\tstatus code: 400, request id: a3f5d554-2763-53e2-ae64-89ca546cb6ab" app_id=scans-uploader instance=scans-uploader-d7f66bd4f-cn2c2 scope=dapr.runtime type=log ver=1.9.5
```

I really don't get what is the connection between those 2 events, but to make it work, i need to delete my binding, deploy my app, and reapply my binding

Worth mentioning that my binding works great , as one pod (no side car attached) receive correctly the messages from SQS

**Comment by ItalyPaleAle** [comment]
@robertojrojas could you please take a look at this?

**Comment by robertojrojas** [comment]
@ItalyPaleAle I'll take a deeper look early next week, but my first impression is that there might be an Authorization problem related to this.

**Comment by robertojrojas** [comment]
@steve-heslouin @ItalyPaleAle 
I've tried different scenarios with without permissions to an existing and non-existing Queue and I got the same error on both: 
```
AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist or you do not have access to it.
        status code: 400, request id: 69ba7c1c-b253-5034-ad36-20bd8f09b1d2
```
The AWS SQS Bindings Init process performs a [client.GetQueueUrlWithContext](https://github.com/dapr/components-contrib/blob/master/bindings/aws/sqs/sqs.go#L73), which appears to be section of the code that returns the error above. 

I did some research and sections **Cross account GetQueueUrl** and **Insufficient permissions**, among others in the following document explain situations that would cause the above error. https://repost.aws/knowledge-center/sqs-queuedoesnotexist-errors

I hope that helps!

**Comment by steve-heslouin** [comment]
@ItalyPaleAle Thanks for checking it out ;) Unfortunately, as stated in my first post, during the test, i've given my worker node IAM role `sqs:*` and the input binding do send the messages from the SQS queue to my app listening on `/${metadata.name}`

Talking of which, instead of giving SQS at worker node level, can i use IRSA and do something like :
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sqs-bindings
spec:
  type: bindings.aws.sqs
  version: v1
  metadata:
  - name: queueName
    value: myqueue
  - name: region
    value: us-east-1
  spec:
    serviceAccountName: sqs-access-irsa
```

Thanks a lot
