### ISSUE TITLE
PubSub retries only four times since 1.10

### ISSUE THREAD

**Issue by jrehnen** [dapr/components-contrib#2757]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.10.4

## Expected Behavior

On event failure (reported by the container as RETRY), dapr should continue to deliver the event to the container whenever no event is currently handled.

## Actual Behavior

The event is retried three times and is then discarded.

```
time="2023-04-05T12:42:23.180542344Z" level=debug msg="Received batch with 1 events on topic cloud.dev.train, partition 10" app_id=cloud-dev-icgraffiti-logic-producer component="az-eh-intercitytransportgraffiti-logic-producer-sub (pubsub.azure.eventhubs/v1)" instance=cloud-dev-icgraffiti-logic-producer-556559d86d-wwqln scope=dapr.contrib type=log ver=1.10.4
time="2023-04-05T12:42:23.180798926Z" level=debug msg="Processing EventHubs event cloud.dev.train/(nil) (attempt: 1)" app_id=cloud-dev-icgraffiti-logic-producer component="az-eh-intercitytransportgraffiti-logic-producer-sub (pubsub.azure.eventhubs/v1)" instance=cloud-dev-icgraffiti-logic-producer-556559d86d-wwqln scope=dapr.contrib type=log ver=1.10.4
time="2023-04-05T12:42:23.550009769Z" level=warning msg="Error processing EventHubs event: cloud.dev.train/(nil). Retrying..." app_id=cloud-dev-icgraffiti-logic-producer component="az-eh-intercitytransportgraffiti-logic-producer-sub (pubsub.azure.eventhubs/v1)" instance=cloud-dev-icgraffiti-logic-producer-556559d86d-wwqln scope=dapr.contrib type=log ver=1.10.4
time="2023-04-05T12:42:28.408282418Z" level=info msg="HTTP API Called" app_id=cloud-dev-icgraffiti-logic-producer instance=cloud-dev-icgraffiti-logic-producer-556559d86d-wwqln method="GET /v1.0/healthz" scope=dapr.runtime.http-info type=log useragent=kube-probe/1.25 ver=1.10.4
time="2023-04-05T12:42:28.408282506Z" level=info msg="HTTP API Called" app_id=cloud-dev-icgraffiti-logic-producer instance=cloud-dev-icgraffiti-logic-producer-556559d86d-wwqln method="GET /v1.0/healthz" scope=dapr.runtime.http-info type=log useragent=kube-probe/1.25 ver=1.10.4
time="2023-04-05T12:42:28.551006476Z" level=debug msg="Processing EventHubs event cloud.dev.train/(nil) (attempt: 2)" app_id=cloud-dev-icgraffiti-logic-producer component="az-eh-intercitytransportgraffiti-logic-producer-sub (pubsub.azure.eventhubs/v1)" instance=cloud-dev-icgraffiti-logic-producer-556559d86d-wwqln scope=dapr.contrib type=log ver=1.10.4
time="2023-04-05T12:42:33.670894441Z" level=debug msg="Processing EventHubs event cloud.dev.train/(nil) (attempt: 3)" app_id=cloud-dev-icgraffiti-logic-producer component="az-eh-intercitytransportgraffiti-logic-producer-sub (pubsub.azure.eventhubs/v1)" instance=cloud-dev-icgraffiti-logic-producer-556559d86d-wwqln scope=dapr.contrib type=log ver=1.10.4
time="2023-04-05T12:42:33.73355323Z" level=debug msg="Received client for partition 2" app_id=cloud-dev-icgraffiti-logic-producer component="az-eh-intercitytransportgraffiti-logic-producer-sub (pubsub.azure.eventhubs/v1)" instance=cloud-dev-icgraffiti-logic-producer-556559d86d-wwqln scope=dapr.contrib type=log ver=1.10.4
time="2023-04-05T12:42:34.41524811Z" level=info msg="HTTP API Called" app_id=cloud-dev-icgraffiti-logic-producer instance=cloud-dev-icgraffiti-logic-producer-556559d86d-wwqln method="GET /v1.0/healthz" scope=dapr.runtime.http-info type=log useragent=kube-probe/1.25 ver=1.10.4
time="2023-04-05T12:42:34.415486446Z" level=info msg="HTTP API Called" app_id=cloud-dev-icgraffiti-logic-producer instance=cloud-dev-icgraffiti-logic-producer-556559d86d-wwqln method="GET /v1.0/healthz" scope=dapr.runtime.http-info type=log useragent=kube-probe/1.25 ver=1.10.4
time="2023-04-05T12:42:34.456952577Z" level=debug msg="Received batch with 0 events on topic cloud.dev.train, partition 18" app_id=cloud-dev-icgraffiti-logic-producer component="az-eh-intercitytransportgraffiti-logic-producer-sub (pubsub.azure.eventhubs/v1)" instance=cloud-dev-icgraffiti-logic-producer-556559d86d-wwqln scope=dapr.contrib type=log ver=1.10.4
time="2023-04-05T12:42:38.796390888Z" level=debug msg="Processing EventHubs event cloud.dev.train/(nil) (attempt: 4)" app_id=cloud-dev-icgraffiti-logic-producer component="az-eh-intercitytransportgraffiti-logic-producer-sub (pubsub.azure.eventhubs/v1)" instance=cloud-dev-icgraffiti-logic-producer-556559d86d-wwqln scope=dapr.contrib type=log ver=1.10.4
time="2023-04-05T12:42:38.892695158Z" level=error msg="Too many failed attempts at processing Eventhubs event: cloud.dev.train/(nil). Error: <nil>" app_id=cloud-dev-icgraffiti-logic-producer component="az-eh-intercitytransportgraffiti-logic-producer-sub (pubsub.azure.eventhubs/v1)" instance=cloud-dev-icgraffiti-logic-producer-556559d86d-wwqln scope=dapr.contrib type=log ver=1.10.4
```

If we try to define a resilience policy to enforce infinite retries (which should be default behaviour), it discards the event after a single RETRY instead.

```
time="2023-04-05T12:38:27.287557896Z" level=debug msg="Received batch with 1 events on topic cloud.dev.train, partition 16" app_id=cloud-dev-icgraffiti-logic-producer component="az-eh-intercitytransportgraffiti-logic-producer-sub (pubsub.azure.eventhubs/v1)" instance=cloud-dev-icgraffiti-logic-producer-fb6f45f69-cqz9f scope=dapr.contrib type=log ver=1.10.4
time="2023-04-05T12:38:27.287968976Z" level=debug msg="Processing EventHubs event cloud.dev.train/(nil) (attempt: 1)" app_id=cloud-dev-icgraffiti-logic-producer component="az-eh-intercitytransportgraffiti-logic-producer-sub (pubsub.azure.eventhubs/v1)" instance=cloud-dev-icgraffiti-logic-producer-fb6f45f69-cqz9f scope=dapr.contrib type=log ver=1.10.4
time="2023-04-05T12:38:27.444810791Z" level=info msg="Error processing operation component[az-eh-intercitytransportgraffiti-logic-producer-sub] input. Retrying in 381.223322ms…" app_id=cloud-dev-icgraffiti-logic-producer instance=cloud-dev-icgraffiti-logic-producer-fb6f45f69-cqz9f scope=dapr.runtime type=log ver=1.10.4
time="2023-04-05T12:38:27.444909868Z" level=debug msg="Error for operation component[az-eh-intercitytransportgraffiti-logic-producer-sub] input was: RETRY status returned from app while processing pub/sub event 863f6578-f877-430e-82aa-2fcf19a252fd" app_id=cloud-dev-icgraffiti-logic-producer instance=cloud-dev-icgraffiti-logic-producer-fb6f45f69-cqz9f scope=dapr.runtime type=log ver=1.10.4
```
After the last log line, the event is never heard from again.

## Steps to Reproduce the Problem

Deploy a rudimentary pubsub app which always fails by returning the TopicEventResponse("retry").
Subscribe to the EventHub with a component:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: az-eh-intercitytransportgraffiti-logic-producer-sub
spec:
  type: pubsub.azure.eventhubs
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        key: AzureEventHubConnectionStringSubscriber
        name: secret-name
    - name: storageAccountName
      value: storageaccountname
    - name: storageAccountKey
      secretKeyRef:
        key: AzureEventCheckpointStorageKey
        name: secret-name
    - name: storageContainerName
      value: azure-webjobs-eventhub
```
Fill the EventHub with some events. Content shouldn't matter for this example.
To reproduce the behaviour with the resilience policy, add the following to the cluster:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: myresiliency
# similar to subscription and configuration specs, scopes lists the Dapr App IDs that this
# resiliency spec can be used by.
scopes: []
spec:
  # policies is where timeouts, retries and circuit breaker policies are defined.
  # each is given a name so they can be referred to from the targets section in the resiliency spec.
  policies:
    # timeouts are simple named durations.
    timeouts:
      general: 30s
    # retries are named templates for retry configurations and are instantiated for life of the operation.
    retries:
      retryForever:
        policy: constant
        maxInterval: 15s
        maxRetries: -1 # retry indefinitely

    # circuit breakers are automatically instantiated per component and app instance.
    # circuit breakers maintain counters that live as long as the Dapr sidecar is running. They are not persisted.
    circuitBreakers: {}

  # targets are what named policies are applied to. Dapr supports 3 target types - apps, components and actors
  targets:
    apps: {}

    actors: {}

    components:
        az-eh-intercitytransportgraffiti-logic-producer-sub:
            inbound:
                timeout: general
                retry: retryForever
```

## Release Note

RELEASE NOTE: **FIX**
