### ISSUE TITLE
secretstores.local.env duplicates key name

### ISSUE THREAD

**Issue by BartNetJS** [dapr/components-contrib#2838]
I have a kubernetes secret store called for example mysecrets
In DAPR I defined the secret store like this:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-secretstore
  namespace: {{ .Values.namespace }}
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
```

Via c# with the sdk i retrieve the secrets like this:
daprClient.GetSecretAsync("my-secretstore", "mysecrets");

That works fine, i got a dictionary back with key/value pairs.

On my local dev machine my DAPR secret store looks like this:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name:my-secretstore
spec:
  type: secretstores.local.env
  version: v1
```

But when i the call daprClient.GetSecretAsync("my-secretstore", "mysecrets");
I got one key/value pair with key named 'mysecrets', and the value is the JSON with the real properties and secrets.

I also saw in the test for the environment store this test:

![image](https://github.com/dapr/components-contrib/assets/4865355/702b5e6a-1bbb-4e13-920c-35601b84e3f4)

It seems a bug.
Or do I use it wrong?
