### ISSUE TITLE
Kafka Binding v1.10.7: consumer/broker/0 disconnecting due to error processing FetchRequest: EOF\n

### ISSUE THREAD

**Issue by Andemki** [dapr/components-contrib#2874]
## What version of Dapr?

1.10.7

## Expected Behavior

Dapr and Azure Event Hub integration using Kafka binding work without errors

## Actual Behavior

I've been using bindings.kafka component for recieving messages from Azure Event Hub in my application. Everything work properly in Dapr versions 1.8.7. But when I updated dapr components to version 1.10.7, my application stopped receiving new messages from EventHub. I've noticed the following error message in the sidecar container (daprd):

>2023-05-30 17:50:14 time="2023-05-30T16:50:14.5142882Z" level=debug msg="consumer/broker/0 disconnecting due to error processing FetchRequest: EOF\n" app_id=my-eventhublistener component="my-eventhub-receiver (bindings.kafka/v1)" instance=f3688891ba8e scope=dapr.contrib type=log ver=1.10.7

The last working version is 1.8.7. Starting from Dapr v.1.9.0 the Kafka binding component doesn't work for us.

Yaml output of my bindings.kafka component:

```
apiVersion: dapr.io/v1alpha1
auth:
  secretStore: my-kv-secrets
kind: Component
metadata:
  annotations:
    meta.helm.sh/release-name: my-eventhublistener
    meta.helm.sh/release-namespace: my-namespace
  labels:
    app.kubernetes.io/managed-by: Helm
  name: my-eventhub-receiver
  namespace: my-namespace
spec:
  metadata:
  - name: brokers
    value: my-eh-namespace.servicebus.windows.net:9093
  - name: topics
    value: my-eh-data
  - name: consumerGroup
    value: my-eventhublistener
  - name: authRequired
    value: "true"
  - name: saslUsername
    value: $ConnectionString
  - name: saslPassword
    secretKeyRef:
      key: eventhub-connectionstring
      name: eventhub-connectionstring
  type: bindings.kafka
  version: v1
```

## Steps to Reproduce the Problem

1. Create a kafka.binding component to receive messages from Event Hub in your ASP.Net Core application
3. Deploy your application and the component to the Kubernetes
4. Check that your application doesn't receive messages from Event Hub

**Comment by berndverst** [comment]
Possibly related to https://github.com/Shopify/sarama/issues/913

**Comment by berndverst** [comment]
The error itself comes from the `sarama` library

**Comment by berndverst** [comment]
@Andemki the `sarama` library defaults to Kafka version `2.0.0`. It is unclear whether EventHubs actually supports this.

Can you set the `version` in the kafka binding metadata to `1.0.0` and try that please?

**Comment by berndverst** [comment]
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-binding
spec:
  type: bindings.kafka
  version: v1
  metadata:
  - name: version # YOU LIKELY MUST SET THIS FOR EVENTHUBS
    value: 1.0.0
```

I omitted the other metadata in this example - but I just wanted to highlight how this must be configured.
