### ISSUE TITLE
Where do I safely store the New Relic License Key when connecting a DAPR sidecar to New Relic?

### ISSUE THREAD

**Issue by bb-avi** [dapr/components-contrib#2876]
The [documentation](https://docs.dapr.io/operations/monitoring/tracing/newrelic/) shows to embed the Key in the URL.  But the Key is a secret and I'd prefer not to put it in the configuration file.  

Is there any way to do this?  

- Can I reference a secret store and embed a secret in the URL?
- Can I add a header name and value under `zipkin` and reference a secret store? 
  - [New Relic accepts the querystring parameters as headers](https://docs.newrelic.com/docs/distributed-tracing/trace-api/report-zipkin-format-traces-trace-api/)

What the documentation shows (for reference):
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "https://trace-api.newrelic.com/trace/v1?Api-Key=<NR-INSIGHTS-INSERT-API-KEY>&Data-Format=zipkin&Data-Format-Version=2"
```

What I would suggest - since [New Relic accepts the querystring parameters as headers](https://docs.newrelic.com/docs/distributed-tracing/trace-api/report-zipkin-format-traces-trace-api/):
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "https://trace-api.newrelic.com/trace/v1"
      headers:
      - name: Data-Format
        value: zipkin
      - name: Data-Format-Version
        value: 2
      - name: Api-Key
        secretKeyRef:
          name: NEW_RELIC_LICENSE_KEY
          key: NEW_RELIC_LICENSE_KEY
auth:
  secretStore: app-secrets
```
