### ISSUE TITLE
Azure: Dapr fails to obtain the authentication token when using Managed Identity of Azure Web App

### ISSUE THREAD

**Issue by jogobella00** [dapr/components-contrib#2913]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.11.0

## Expected Behavior

On startup of the sidecar Dapr will get the authentication token using System Assigned Managed Identity of the Azure Web App and generate components that will communicate with Azure services.

## Actual Behavior

Fails to obtain the auth token:

`level=fatal msg="process component binding-azure-storage-my-component error: [INIT_COMPONENT_FAILURE]: initialization error occurred for binding-azure-storage-my-component (bindings.azure.blobstorage/v1): failed to create Azure Storage container myContainer: ChainedTokenCredential: failed to acquire a token.\nAttempted credentials:\n\tmanaged identity\n\tAzureCLICredential: Azure CLI not found on path" app_id="$Default" instance=<redacted> scope=dapr.runtime type=log ver=1.11.0`

After encountering this error I tried to have workaround by installing the Azure CLI in the docker image of the Azure Web App, but then Dapr times out when creating the component:

`level=fatal msg="process component biding-azure-storage-my-component error: [INIT_COMPONENT_FAILURE]: initialization error occurred for biding-azure-storage-my-component (bindings.azure.blobstorage/v1): init timeout for component biding-azure-storage-my-component exceeded after 5s" app_id="$Default" instance=<redacted> scope=dapr.runtime type=log ver=1.11.0`

## Steps to Reproduce the Problem

Create an Azure Web App with System Assigned Managed Identity.
Build a docker image with your app and Dapr.

Inject Dapr component to the Web App, make sure that this component will use System Assigned Managed Identities to authenticate in Azure e.g.:
```yaml 
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: binding-azure-storage-my-component
  namespace: default
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
  - name: storageAccount
    value: <storageAccountName>
  - name: container
    value: <containerName>
```

Start the application.

*Issue is __not__ existing in the previous Dapr version (1.10.7).

## Release Note

RELEASE NOTE: **FIX** Dapr to obtain authentication token when using Managed Identity of Azure Web App.
