### ISSUE TITLE
Azure Eventhub with Kafka interface PubSub not working

### ISSUE THREAD

**Issue by pyjads** [dapr/components-contrib#2919]
I am trying to use dapr with Kafka Interface for Azure Eventhub. However, I get the below error:

```
level=debug msg="kafka: error while consuming data-event-consumer/2: EOF" app_id=event-consumer component="events-pubsub (pubsub.kafka/v1)" instance=recorder-c │
│ onsumer-84dd95b8d4-b67kl scope=dapr.contrib type=log ver=1.10.7
```

Below is my yaml file:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: events-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: events-dev.servicebus.windows.net:9093
    - name: consumerGroup
      value: "xyz"
    - name: authRequired
      value: "true"
    - name: authType
      value: "password"
    - name: saslUsername
      value: $ConnectionString
    - name: saslPassword
      value: <azure eventhub connection-string>
    - name: maxMessageBytes
      value: 5000
    - name: consumeRetryInterval
      value: 1s
```
