### ISSUE TITLE
OIDC (bearer) middleware is not working in version 1.11.2.  

### ISSUE THREAD

**Issue by ben-kotvis** [dapr/components-contrib#3025]
## Expected Behavior

When I spin up a new cluster in Kubernetes or in a dev environment and add a bearer middleware to a configuration I expect to get a successful response if I check the JWT in (JWT.io) to make sure the issuer and audience are correct and they are correct.  

## Actual Behavior

I get a 401 all the time no matter what.  

## Steps to Reproduce the Problem

1. Spin up a new environment (1.11.2) and use bearer middleware on an app
2. Call the endpoint with a valid token
3. You will always get a 401

If you use version 1.9.0 it works.  Also, 1.10.0 works as well.  So it was introduced somewhere between 1.10.0 and 1.11.2.

**Comment by ItalyPaleAle** [comment]
Can you  share the Component YAML you are using please?

**Comment by ben-kotvis** [comment]
> Can you share the Component YAML you are using please?

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: bearertoken
spec:
  type: middleware.http.bearer
  version: v1
  metadata:
  - name: authority
    value: "[guid removed]" 
  - name: issuer
    value: "https://login.microsoftonline.com/[guid removed]/v2.0"
```


Here is the config:
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  httpPipeline:
    handlers:
    - name: bearertoken
      type: middleware.http.bearer
```
