### ISSUE TITLE
PubSub Redis does not clear the consumed messages

### ISSUE THREAD

**Issue by cilerler** [dapr/components-contrib#3100]
The code below works just fine with RabbitMQ and Azure ServiceBus Queue and Topic.  However, when I use it with Redis, it doesn't clear the acknowledged records (`HTTP 200`).  Any ideas on how to fix it?

```csharp
    app.MapPost("/orders", [Dapr.Topic(DAPR_PUBSUB_STORE, "orders")] (Order order) =>
    {
        Task.Delay(TimeSpan.FromSeconds(10)).Wait();
        Util.Highlight($"Subscriber received : {order}").Dump();
        if (order.OrderId.ToString().EndsWith("6"))
        {
            Util.WithStyle($"Mimic an error", "background-color: #FF0000; color: #FFFFFF;").Dump("Check this out");
            return Results.Problem("There is a problem");
        }
        return Results.Ok(order);
    });
```

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-redis
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: "passwordadmin"
```

![image](https://github.com/dapr/components-contrib/assets/385958/2746b84f-4377-42f0-9936-e70875d9dfce)
