### ISSUE TITLE
support specifying number of partitions for Kafka pubsub component

### ISSUE THREAD

**Issue by olitomlinson** [dapr/components-contrib#3110]
## Describe the feature

[As discussed with Bernd on discord](https://discord.com/channels/778680217417809931/901141467840524289/1146918875443757216) 

It would be highly convenient in dev/test scenarios, if dapr provided a metadata configuration to specify the default number of partitions for any topic, for a given kafka pubsub component.

The kafka server env var to configure the default partition count is  `KAFKA_NUM_PARTITIONS` so maybe a familiar metadata property name could be `numPartitions`

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers # Required. Kafka broker connection setting
    value: "kafka:29092"
  - name: consumerGroup
    value: "{namespace}"
  - name: clientID 
    value: "workflow-client"
  - name: numPartitions
  - value: [int, greater than 0] [if not specified, assume default behaviour of sarama client]
```

## Release Note

RELEASE NOTE:
