### ISSUE TITLE
Kafka pubsub connection refused

### ISSUE THREAD

**Issue by orion6dev** [dapr/components-contrib#3113]
I engaged in a conversation with @olitomlinson on this [GitHub thread](https://github.com/dapr/dapr/issues/6843). Subsequently, I attempted to execute all of my services within a Docker Compose setup, similar to the approach demonstrated in [olitomlinson's dapr-workflow-examples repository](https://github.com/olitomlinson/dapr-workflow-examples). The outcome was quite successful; I was able to run all of my microservices and debug a single microservice in my IDE. This was an unexpectedly positive outcome arising from our discussion.

I can call end-points like `POST http://localhost:3500/v1.0/state/statestore` to store data.

However, I can't get the pub-sub to work.

This is my component file:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: scanner
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "host.docker.internal:9092"
    - name: authType
      value: "none"
    - name: authRequired
      value: "false"
    - name: disableTls
      value: "true"
```

As one can see, I use `host.docker.internal:9092`as the broker's address. All works well. The broker is found:

```
2023-09-04 16:01:27 time="2023-09-04T14:01:27.663691712Z" level=debug msg="Found brokers: [host.docker.internal:9092]" app_id=scanner component="scanner (pubsub.kafka/v1)" instance=a2c3d8e89fb9 scope=dapr.contrib type=log ver=1.11.3
```

But when I call

```
POST http://localhost:3500/v1.0/publish/scanner/scan
Content-Type: application/json

{
  "payload": "0BC59FD3-C8D0-4EAD-84B0-0EF812F86148"
}
```

I am getting this message

```
{
  "errorCode": "ERR_PUBSUB_PUBLISH_MESSAGE",
  "message": "error when publish to topic scan in pubsub scanner: dial tcp 127.0.0.1:9092: connect: connection refused"
}
```

Why does it try to reach `127.0.0.1:9092` instead of `host.docker.internal:9092` as defined in the component file?

Replacing `host.docker.internal:9092` with `kafka:9092` (`kafka` being the service name), does not have any effect.  It still tries to call `127.0.0.1:9092`.

Am I overlooking something? I looked in the source code but could not find anything. But then again, I am not a GO developer.

**Comment by olitomlinson** [comment]
hey @orion6dev -- glad you have had some success!

I'm pretty sure I remember having this same problem when I was trying to get Kafka working initially, but I can't remember what I did. Although I remember doing a lot of fiddling around and eventually got it working. Word of warning : I'm not a kafka expert so my configuration is highly likely to not be correct, but it works for dev'ing.

I actually have a branch on the same repo, specifically for using kafka called `kafka2` which works just fine for using pubsub, and for debugging.

The only thing I can suggest is that you go line-by-line through the compose definition of your kafka service and inspect any significant differences, compared to mine?

https://github.com/olitomlinson/dapr-workflow-examples/blob/c35a2304317496ee99fa097855235635d3582eb4/compose.yml#L150C2-L175C30

it's also worth noting that I am using a different value for the kafka `brokers` compared to you :

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers # Required. Kafka broker connection setting
    value: "kafka:29092"
```
