### ISSUE TITLE
[Proposal] Distributed outbound rate-limiting

### ISSUE THREAD

**Issue by sujitdmello** [dapr/components-contrib#3139]
In a recent DAPR project, we implemented a distributed rate-limiting feature using DAPR state to throttle calls made by the HTTP binding to internal services, so as to honor service limits and budgets. This proved really key in the message processing scenario as it prevented these existing services from  being overwhelmed by numerous API calls. The project was implemented in Java using the token-bucket library Bucket4j.

It seemed like this may be a useful addition to the HTTP Binding itself, so we did some spikes and created a sample approach and design proposal for integrating a distributed token bucket into DAPR using DAPR State. An existing rate limiting library in Golang was forked and a sample created. You can find it [here](https://github.com/sujitdmello/go-limiter/blob/add-dapr/daprsample/README.md) along with a potential proposal for the HTTP binding (summarized below).

- maxCallsPerPeriod - the maximum number of calls allowed per period
- period - the period of time in which the maximum number of calls is allowed
- rateLimitStore - the name of the DAPR state store to use for the rate-limiting

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: http-person-service
spec:
  type: bindings.http
  version: v1
  metadata:
    - name: url
      value: http://localhost:8089/participant
    - name: maxCallsPerPeriod
      value: "10"
    - name: period
      value: "1s"
    - name: rateLimitStore
      value: "redis-rate-limit"
```
