### ISSUE TITLE
Add SendGrid output binding for sending emails 

### ISSUE THREAD

**Issue by amanbha** [dapr/components-contrib#314]
## Describe the proposal.
Add an output binding for SendGrid
This sends simple HTML emails using the SendGrid API. 

Example component
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sendgrid
spec:
  type: bindings.twilio.sendgrid
  metadata:
  - name: emailFrom
    value: "testapp@dapr.io" # optional 
  - name: emailTo
    value: "dave@dapr.io" # optional 
  - name: subject
    value: "Hello!" # optional 
  - name: apiKey
    value: "CHANGEME" # required, this is your SendGrid key
```

The data field in the binding request is used as email body
You can specify any of the metadata properties on the request too (e.g. `emailFrom`, `emailTo`, `subject`)

Example payload
```
{
  "metadata": {
    "emailTo": "changeme@example.net",
    "subject": "An email from Dapr SendGrid binding"
  }, 
  "data": "<h1>Testing Dapr Bindings</h1>This is a test.<br>Bye!"
}
```
