### ISSUE TITLE
Trouble with shutting down of resources while request is in progress

### ISSUE THREAD

**Issue by pyjads** [dapr/components-contrib#3166]
```yml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: abc-scale
spec:
  scaleTargetRef:
    name: abc-deployment
  pollingInterval: 600                               
  cooldownPeriod:  300                         
  minReplicaCount: 0                          
  maxReplicaCount: 10
  advanced:
    restoreToOriginalReplicaCount: true
  triggers:
  - type: rabbitmq
    metadata:
      mode: QueueLength # QueueLength or MessageRate
      value: "1" # message backlog or publish/sec. target per instance
      queueName: {{queue}}
      # unsafeSsl: "true"
    authenticationRef:
        name:  azure-key-vault-keda-authentication
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-key-vault-keda-authentication
spec:
  podIdentity:
    provider: azure
  azureKeyVault:                                                        
    vaultUri: https://{{key_vault_name}}.vault.azure.net/                              
    podIdentity:                                                         
      provider: azure                                                 
      identityId: "myidentity"                           
    cloud:                                                              
      type: AzurePublicCloud
    secrets:                                                            
    - parameter: host
      name: connection-key
```

Above is the configuration I am using for one of the applications. The challenge I am facing currently is:

I have a parser that parses a message from rabbitmq in 30 - 70 minutes. It takes 30 - 70 minutes to process a message depending on the file size mentioned in the message (super complex parser).

As soon as the message is pushed into the rabbitmq, I want the workers to scale. If 7 messages are in the queue, The pods should be scaled to 7 which is happening. Some of the messages are processed in 30 minutes while some takes 70 minutes. The problem is Keda shut down the workers that are still processing the event. This results is reprocessing of the file again by some other worker as the worker processing it was shut down by keda. Sometimes this results in re processing of file 2 3 times before it is finished.

Is there any feature in Keda like pollingInterval time should be only for scaling up and some other attribute only for scaliing down?
How can I resolve this?

Currently it is resulting in wastage of resources and also increased time. Setting polling interval to 70 minutes is also not feasible as the worker should be started for processing as soon as possible with minimum delay.
