### ISSUE TITLE
error claiming pending Redis messages

### ISSUE THREAD

**Issue by et2012** [dapr/components-contrib#3184]
## Actual Behavior

`dapr` sidecar spams error logs:
```
time="2023-10-19T07:21:51.707278516Z" level=error msg="error claiming pending Redis messages: redis: nil" app_id=api-notice component="pubsub (pubsub.redis/v1)" instance=api-notice-dapr-57f5b96777-nqj7l scope=dapr.contrib type=log ver=1.12.0
```

## Steps to Reproduce the Problem

- Install `dapr` `1.11.4` on kubernetes
- Create `pubsub` component:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  metadata:
    - name: redisHost
      value: 'redis-master:6379'
    - name: redisPassword
      value: 'password'
  type: pubsub.redis
  version: v1
```
- Upgrade `dapr` from `1.11.4` to `1.12.0`
```
kubectl replace -f https://raw.githubusercontent.com/dapr/dapr/5a15b3e0f093d2d0938b12f144c7047474a290fe/charts/dapr/crds/configuration.yaml
dapr upgrade -k --runtime-version 1.12.0
```
- Create `statestore` component and enable `outbox` pattern
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore.outbox
  namespace: default
spec:
  metadata:
    - name: connectionString
      value: >-
        Server=sqlserver;Database=dapr;User
        Id=dapr_user;Password=dapr_password;
    - name: outboxPublishPubsub
      value: 'pubsub'
    - name: outboxPublishTopic
      value: 'outbox-event'
  type: state.sqlserver
  version: v1
```
- Upsert several states to `outbox`
```
dapr.ExecuteStateTransactionAsync("statestore.outbox", new List<StateTransactionRequest>()
{
new ($"{order.Id}", JsonSerializer.SerializeToUtf8Bytes(order), StateOperationType.Upsert)
});
```
- `outbox` and `pubsub` work fine but `dapr` sidecar spams error logs

## Release Note

RELEASE NOTE: **FIX** error claiming pending Redis messages
