### ISSUE TITLE
Local env secret store can't read env set by Multi-App Run

### ISSUE THREAD

**Issue by heunghingwan** [dapr/components-contrib#3187]
when using multi-app run `dapr run -f .` you can set environment variables in dapr.yaml:

```
version: 1
apps:
  - appID: api
    appDirPath: ./services/api/
    env:
      MYAPP_API_PORT: 3000
    command: ["yarn","run", "start"]
```
but this environment variable is missing from secret store
