### ISSUE TITLE
Azure SQL State Error: Can't use AAD auth fields

### ISSUE THREAD

**Issue by alicejgibbons** [dapr/components-contrib#3189]
## Expected Behavior
Using AAD auth with either client certificate or client secret credentials should work when creating an Azure SQL state Dapr component. This was tested using Dapr 1.12.0 locally.

## Actual Behavior
Both Azure Client Secret and Azure Client Certificate auth methods fail with the following error:
``` text
FATA[0004] Fatal error from runtime: process component statestore error: [INIT_COMPONENT_FAILURE]: initialization error occurred for statestore (state.sqlserver/v1): [INIT_COMPONENT_FAILURE]: initialization error occurred for statestore (state.sqlserver/v1): failed to create database: ChainedTokenCredential authentication failed
POST https://login.microsoftonline.com/<REDACTED>/oauth2/v2.0/token
--------------------------------------------------------------------------------
RESPONSE 400 Bad Request
--------------------------------------------------------------------------------
{
  "error": "invalid_scope",
  "error_description": "AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://database.windows.net openid offline_access profile is not valid. Trace ID: <REDACTED> Correlation ID: <REDACTED> Timestamp: 2023-10-23 22:55:33Z",
  "error_codes": [
    70011
  ],
  "timestamp": "2023-10-23 22:55:33Z",
  "trace_id": "<REDACTED>",
  "correlation_id": "<REDACTED>"
}
```

Note: I tried the same service principle on a CosmosDB component (with appropriate resource access) and it worked fine.

## Steps to Reproduce the Problem

1. Run dapr state management quickstart locally
2. Create a Dapr Azure SQL component like the following:

``` yaml
apiVersion: cra.diagrid.io/v1beta1
kind: Component
metadata:
  name: statestore
spec:
  type: state.sqlserver
  version: v1
  metadata:
    - name: useAzureAD
      value: true
    - name: connectionString
      value: >-
        sqlserver://<redacted>.database.windows.net:1433?database=db1;
    - name: azureTenantId
      value: REDACTED
    - name: azureClientId
      value: REDACTED
    - name: azureClientSecret
      value: REDACTED
    - name: azureEnvironment
      value: AzurePublicCloud
```

3. Follow the instructions for authenticating with Azure AD: https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-sqlserver/#authenticate-using-azure-ad and https://docs.dapr.io/developing-applications/integrations/azure/azure-authentication/howto-aad/
4. Ensure the service principle has the necessary permissions on the Azure SQL DB. I tested with Contributor and Owner perms.

## Release Note

RELEASE NOTE: **FIX** Bug in AAD auth for SQL.
