### ISSUE TITLE
connectionString for Azure SQL

### ISSUE THREAD

**Issue by danobis** [dapr/components-contrib#3191]
I am trying to set up Azure SQL as a state store as described here: https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-sqlserver/

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: concerts-azuresql
spec:
  type: state.sqlserver
  version: v1
  metadata:
    - name: useAzureAD
      value: true
    # Connection string or URL of the Azure SQL database, optionally containing the database
    - name: connectionString
      value: 
```

What kind of connectionString is expected here? There are a few different options listed in Azure, some of them requiring a user ID and password. I have no idea what to enter to make it work.
