### ISSUE TITLE
Consul namespace resolution can no longer lookup hosts such as kubernetes.docker.internal.

### ISSUE THREAD

**Issue by anobleperson** [dapr/components-contrib#3204]
## Expected Behavior

Consul namespace resolution can resolve dns names such as kubernetes.docker.internal.

To develop and test locally we run our dapr services in a mixture of docker-compose and local applications (like vs-code) with the local dapr. Because a service might be running inside a docker container, or on the host machine, we used "kubernetes.docker.internal" to specify the address of the service. 

## Actual Behavior

Changes between 1.11 and 1.12 have meant that dns names can no longer be used, only valid IP addresses can be used. The breaking change was in consul.go:
![image](https://github.com/dapr/components-contrib/assets/2583737/06b3a237-8041-4175-9b0f-c869b0693325)

## Steps to Reproduce the Problem

1. Setup a sample grpc service with Consul defined as
```yaml
  nameResolution:
    component: "consul"
    configuration:
      client:
        address: "kubernetes.docker.internal:8500"
      selfRegister: true
      advancedRegistration:
        name: "${APP_ID}"
        port: ${DAPR_HTTP_PORT}
        address: "kubernetes.docker.internal"
        check:
          name: "Dapr Health Status"
          checkID: "daprHealth:${APP_ID}"
          interval: "15s"
          http: "http://${HOST_ADDRESS}:${DAPR_HTTP_PORT}/v1.0/healthz"
        meta:
          DAPR_PORT: "${DAPR_PORT}"
```
2. Have a client make a call via the dapr proxy to the sample service
3. Note that an error is returned from the dapr proxy saying "invalid ip address kubernetes.docker.internal"

## Release Note

RELEASE NOTE:
