### ISSUE TITLE
Using kafka component to subscribe to multiple topics on dapr of k8s and reporting an error. Sidecar can't get up

### ISSUE THREAD

**Issue by Huawu777** [dapr/components-contrib#3263]
/area runtime

**What version of Dapr?**
1.12.2

**Expected Behavior**
The status of sidecar is running

**Actual Behavior**
![d5ff999418c949e28e7e719caed4f5df](https://github.com/dapr/dapr/assets/14233576/0372dcd1-3e9e-4398-b5d7-d226d9b218d2)

_my component yaml ：_
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: xxx.xxx.xxx.xxx:31092
  - name: authType 
    value: "none"
```

By the way, it works perfectly when subscribing to only one topic.
