### ISSUE TITLE
MongoDB state store returns empty state

### ISSUE THREAD

**Issue by danobis** [dapr/components-contrib#3291]
I am trying to implement MongoDB as a state store. In theory I should be able to swap my existing CosmosDB state store component for a MongoDB one without having to change the code.

Here is the state I am trying to retrieve in CosmosDB (which works fine):

<img width="802" alt="image" src="https://github.com/dapr/components-contrib/assets/68187440/63c47681-f6b8-4f6c-b7c5-f4206ad425cd">

Here it is in MongoDB Atlas:

<img width="1157" alt="image" src="https://github.com/dapr/components-contrib/assets/68187440/587475ea-7d1f-4f60-96d3-dd2b1a8e456a">

Here is the component configuration, I don't get any errors when launching my services so Dapr seems to connect to the database just fine:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: concerts-mongodb
spec:
  type: state.mongodb
  version: v1
  metadata:
    - name: connectionString
      value: mongodb+srv://<username>:<password>@microtickets.ryagnyb.mongodb.net/
    - name: databaseName
      value: microtickets
    - name: collectionName
      value: concerts
```

This is where I try to retrieve the state:

```C#
var stateTest = await daprClient.GetStateAsync<Concert>("concerts-mongodb", "cfb88e29-4744-48c0-94fa-b25b92dea319");
Console.WriteLine("stateTest: " + stateTest.Name);
```

When I change the state store name to my CosmosDB state store, I get the desired result (the name of the concert). However, when using my MongoDB configuration, I get this:

```
== APP == fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
== APP ==       An unhandled exception has occurred while executing the request.
== APP ==       System.NullReferenceException: Object reference not set to an instance of an object.
```

Can someone tell me what I am doing wrong? Thanks!
