### ISSUE TITLE
maxRetries or redisMaxRetries seems to be ignored.

### ISSUE THREAD

**Issue by krab-skunk** [dapr/components-contrib#3352]
## Expected Behavior

Dapr 1.12.4

When my app, connected to pubsub throw an HTTP 429 (RETRY), it should:
 - retry sending the payload 5 times in a row with 1 second difference
 - sleep for 20s
 - retry sending the payload 5 times in a row with 1 second difference
 - sleep for 20s
 - retry sending the payload 5 times in a row with 1 second difference
 - sleep for 20s
- **GIVE UP!!!** ( but it continue for ever)

So far the Resiliency policy does exactly as it should, so nothing to complain here, the `processingTimeout` also work nicely, the only issue is `maxRetries`, as despite i set it up to 3 times, redis constantly try to send me te payload like an infinite loop

here is my config

```yaml
apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: myresiliency
scopes:
spec:
  policies:
    retries:     
      retryFinite:
        policy: constant
        duration: 1s
        maxRetries: 5           
  targets:
    components:
      pubsub:
        inbound:
          retry: retryFinite
  ```
  
  ```yaml
  apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: redisMaxRetries
    value: "3"
  - name: processingTimeout
    value: "20s"
  ```

The isssue seems to come from `maxRetries` in `pubsub.redis` component. Normally after 3 attempt, i would expect redis to stop trying and just give up, but it's not what is happening here 

thanks a lot in advance
