### ISSUE TITLE
Update the holopin.yaml to use the components badge

### ISSUE THREAD

**Issue by marcduiker** [dapr/components-contrib#3394]
Update the `.github/holopin.yaml` file with the following info to set the default [Holopin badge](https://www.holopin.io/sticker/clrqfypv0282430gjx4hys94pc) for this repo:

```yaml
organization: dapr
defaultSticker: clrqfypv0282430gjx4hys94pc
stickers:
  -
    id: clrqfypv0282430gjx4hys94pc
    alias: components-badge
```

Once this is in place, maintainers can award contributors via the Holopin Bot by mentioning the contributors' username in a PR comment when the PR is accepted: `@holopin-bot @username`

---

Please label this as a __good first issue__.
