### ISSUE TITLE
SQS binding with .NET client fails to apply DelaySeconds metadata

### ISSUE THREAD

**Issue by lorenzobrusco** [dapr/components-contrib#3480]
I've encountered an issue when trying to use the `DelaySeconds` parameter with the AWS SQS binding in Dapr using the .NET client. The `DelaySeconds` metadata is being ignored, and messages are being sent to the queue without the specified delay.

#### Environment:
- Dapr Runtime Version: [1.14]
- Dapr .NET SDK Version: [1.13.1]
- Deployment: [docker-compose]

Component Configuration:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: test-queue-component
spec:
  type: bindings.aws.sqs
  version: v1
  metadata:
  - name: queueName
    value: test-queue
  - name: region
    value: eu-central-1
  - name: direction 
    value: "output"
  - name: logLevel
    value: debug
  - name: enableMessage
    value: "true"
```
```csharp
public async Task SendMessageAsync()
{
    var metadata = new Dictionary<string, string>
    {
        { "DelaySeconds", "30" }
    };
    await daprClient.InvokeBindingAsync("test-queue-component", "create", "message", metadata);
}
```

#### Expected Behavior:
The message should be sent to the SQS queue with a delay of 30 seconds before becoming visible.

#### Actual Behavior:
The message is sent to the queue immediately, without any delay. The DelaySeconds metadata appears to be ignored.
Steps to Reproduce:

#### Configure the SQS binding as shown above.
Use the .NET Dapr client to send a message with the DelaySeconds metadata.
Check the SQS queue immediately after sending the message.
Observe that the message is immediately available, without the specified delay.

#### Additional Information:

I've verified that the AWS credentials have the necessary permissions to set message attributes including DelaySeconds.
Using the AWS SDK directly with the same credentials, I'm able to successfully send delayed messages to the same queue.
I've enabled debug logging, but don't see any errors or warnings related to the DelaySeconds parameter.

#### Questions:

Is this a known limitation of the SQS binding?
Are there any workarounds to achieve delayed message sending with the current implementation?
Is there a plan to support DelaySeconds (and potentially other SQS-specific parameters) in future releases?
