### ISSUE TITLE
Initial delay in receiving events via EventHub PubSub components

### ISSUE THREAD

**Issue by sameert89** [dapr/components-contrib#3654]
## Ask your question here
I am trying to implement the dapr pubsub component for Azure Event Hub using dotnet. I am using docker compose and have succesfuly setup the subscription and publishing via Dapr.

I am noticing a strange behavior where the events are getting delayed initially when the containers are up, once allowed to run for sometime (3-5) minutes, the delay disappears (it goes for several hundred seconds to <100 ms). I need help in determining if the behavior is expected or if I am doing something wrong here?

Below is some source code for reference: 

**Program.cs**
```csharp
public class Program
{
    public static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);

        builder.Services.AddControllers().AddDapr();

        builder.Services.AddDaprClient();

        builder.Services.AddScoped<IEventHandler, ConsumerCreatedEventHandler>();
        builder.Services.AddSingleton<EventPublisherService>();

        builder.Services.AddOptions<BrokerOptions>();
        builder.Services.AddSingleton<TimeKeeper>();

        var app = builder.Build();

        app.UseCloudEvents();
        app.MapSubscribeHandler();
        app.MapControllers();
        app.UseAuthorization();
        
        app.Run();
    }

```

**Compose File**
```yaml
services:
  consumer:
    image: redacted
    build:
      context: .
      dockerfile: <path>
    environment:
       PUBSUB_NAME: "my-pubsub"
       TOPIC_NAME: "my-eventhub"
    ports:
      - "8080:8080"
      - "3500:3500"
  dapr:
    image: "daprio/daprd:latest"
    network_mode: "service:consumer"
    depends_on:
      - consumer
    volumes:
      - ./dapr/components.local/:/components
    command: [
    "./daprd",
    "-app-id", "consumer",
    "-app-port", "8080",
    "--resources-path", "/components"
    ]
```
**Programatic subscription using custom attribute** 
```csharp
[PubSub(match: "event.type==\"ConsumerCreated\"")]
    [HttpPost("events/consumer-created")]
    public ActionResult<Result<string>> ProcessConsumerCreatedEvent([FromBody] object ev)
    {
        var consumer = JsonConvert.DeserializeObject<Consumer>(ev.ToString());
        
        logger.LogInformation("Event Received: {ev}, Propagation Time: {time}", ev.ToString(), keeper.GetDiffInMs(consumer.EventStartTime));
        
        return Ok();
    }
```

The way I am testing this is: I check the logs saying dapr has been initialized and then I publish to event hubs immediately and events take a long time to come, once I wait then start publishing the come immediately. I also tried the plain event hub sdk directly and did not se such behavior.

Any help or info is greatly appreciated.
