### ISSUE TITLE
Pubsub.jetstream bulk subscribe feature doesn't seem to work

### ISSUE THREAD

**Issue by fulop-bede** [dapr/components-contrib#3656]
Hi, I'm trying to use the [bulk subscribe](https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-bulk/#example-1) feature with the [jetstream](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-jetstream/) pubsub component, but I'm experiencing issues.

## Expected Behavior
When using the bulk subscribe feature, I expect:

1. Receiving multiple messages in one request in my app
2. The ability to acknowledge or retry each message independently.

## Actual Behavior

Right out of the box, always only one message is delivered in one request to the app endpoint, no matter how many are waiting to be delivered. I've looked at the component implementation and found this [Concurrency](https://github.com/dapr/components-contrib/blob/1132db59d61847cd517b905a8c257a5ab334f19a/pubsub/jetstream/metadata.go#L60) config (this is not in the docs for some reason). When I set this config to `parallel`, the bulk subscription endpoint in my app starts receiving multiple messages in the same request, but unfortunately, using this setting seems to break the ACK mechanism, Dapr starts logging errors like:
`level=error msg="Error while sending ACK for JetStream message transaction-events/{3 2549}: nats: message was already acknowledged"`
I'm using the `explicit` ackPolicy. Without the parallel concurrency setting, the ack policy works as intended, but the bulk message delivery does not.

## Steps to Reproduce the Problem

I'm using the dotnet SDK to subscribe to a topic:
```
app.MapPost("/transaction-events",
        (BulkSubscribeMessage<BulkMessageModel<Event>> bulkMessages) =>
        {
            var responseEntries = bulkMessages.Entries
                .Select(message => new BulkSubscribeAppResponseEntry(message.EntryId, BulkSubscribeAppResponseStatus.SUCCESS))
                .ToList();
            return new BulkSubscribeAppResponse(responseEntries);
        })
    .WithTopic(new()
    {
        PubsubName = config.Value.PubsubName,
        Name = config.Value.Topic
    })
    .WithBulkSubscribe(new()
    {
        TopicName = config.Value.Topic,
        MaxMessagesCount = 100,
        MaxAwaitDurationMs = 10
    });
```

my pubsub.nats component:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-nats
spec:
  type: pubsub.jetstream
  version: v1
  metadata:
  - name: natsURL
    value: "nats://localhost:4222"
  - name: streamName
    value: "transaction-events"
  - name: durableName
    value: "transaction-events-durable"
  - name: queueGroupName
    value: "transaction-events-processor"
  - name: concurrency
    value: "parallel"
  - name: concurrencyMode
    value: "parallel"
  - name: ackPolicy
    value: "explicit"
  - name: ackWait
    value: "2s"
  - name: maxDeliver
    value: "5"
  - name: backOff
    value: "50ms, 1s, 10s"
  - name: maxAckPending
    value: 5000
```

## Observations and Questions
Is the parallel concurrency setting supposed to be used for bulk subscriptions, and if so, is the acknowledgment issue expected behavior?
Why is the concurrency configuration undocumented for this component?
What is the correct configuration to achieve bulk delivery with independent acknowledgment?
