### ISSUE TITLE
Configuration Store on Postgres throws RpcException

### ISSUE THREAD

**Issue by szymon-bernad** [dapr/components-contrib#3720]
## Expected Behavior

Configuration Store on Postgres should return the item for an existing key. Sample call using .NET SDK:
> var cfg = await daprClient.GetConfiguration("app-cfg", ["get-rnd-exch"]);

## Actual Behavior

GetConfiguration() throws DaprException with 
> InnerException = {Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="failed to get [get-rnd-exch] from Configuration store app-cfg: invalid key : 'get-rnd-exch'")

## Steps to Reproduce the Problem

* Tested with `edge`, 1.15.1, 1.15.3 dapr/daprd  docker images with Docker Compose project.
* Confirmed that Configuration Store component is loaded correctly:
> 2025-03-30 12:03:45 time="2025-03-30T10:03:45.983700171Z" level=info msg="Component loaded: app-cfg (configuration.postgresql/v1)" app_id=dapr-dashboard-api instance=a1e18ae26f01 scope=dapr.runtime.processor type=log ver=1.15.3
* The same code works after switching to Configuration Store on Redis.

1. Add component yaml for Configuration Store:
```
 apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: app-cfg
  namespace: savings
spec:
  type: configuration.postgresql
  version: v1
  metadata:
    # Connection string
    - name: connectionString
      value: "host=postgres user=postgres password=example port=5432 connect_timeout=65 database=config-store"
    # Name of the table which holds configuration information
    - name: table
      value: "pgcfg" 
```

2. Configuration table setup as described in the docs:
> CREATE TABLE IF NOT EXISTS pgcfg (
  KEY VARCHAR NOT NULL,
  VALUE VARCHAR NOT NULL,
  VERSION VARCHAR NOT NULL,
  METADATA JSON
);

3. Config entry inserted using following command:
> INSERT INTO public.pgcfg(
	key, value, version)
	VALUES ('get-rnd-exch', 'true', '1.0');

4. Run .NET app that tries to fetch config key via DaprClient:
```
var cfg = await daprClient.GetConfiguration("app-cfg", ["get-rnd-exch"]);

if (cfg.Items.TryGetValue("get-rnd-exch", out var genRandomExchangeSummary) &&
       bool.TryParse(genRandomExchangeSummary.Value, out var genRandomExchangeSummaryValue))
{
     flagValue = genRandomExchangeSummaryValue;
 }
```
5. Find error log in the dapr container logs:
> 2025-03-30 12:28:16 time="2025-03-30T10:28:16.19323875Z" level=error msg="invalid key : 'get-rnd-exch'" app_id=dapr-dashboard-api component="app-cfg (configuration.postgresql/v1)" instance=a1e18ae26f01 scope=dapr.contrib type=log ver=1.15.3
