### ISSUE TITLE
Dapr state store query failed: invalid output

### ISSUE THREAD

**Issue by freworr** [dapr/components-contrib#3787]
We have a redis state store with redisjson and redisearch enabled. It has the following configuration:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  namespace: siri
  name: notification-redis-cache
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: "redis:6379"
    - name: redisPassword
      value: "password"
    - name: dialTimeout
      value: "30s"
    - name: queryIndexes
      value: |
        [
          {
            "name": "notificationIndex",
            "indexes": [
              {
                "key": "id",
                "type": "TEXT"
              },
              {
                "key": "timeToPublish",
                "type": "NUMERIC"
              }
            ]
          }
        ]
```
And we are using querystateAsync with dotnet to retreive data:
```dotnet
var query = new
        {
            filter = new
            {
                GTE = new
                {
                    timeToPublish = request.TimeToPublish.UtcTicks
                }
            }
        };

        try
        {
            var result = await _daprClient.QueryStateAsync<NotificationData>(
               stateStoreName,
                JsonSerializer.Serialize(query),
                cancellationToken: cancellationToken,
                metadata: Metadata
            );

            var notifications = result.Results.Select(x => x.Data).ToList();
        
            return new FilterResponse
            {
                Notifications = notifications
            };
        }
        catch (DaprException e)
        {
            return new FilterResponse
            {
                Notifications = []
            };
        }
```
When the query state matches no data, it throws the following exception:
```text
Dapr.DaprException: Query state operation failed: the Dapr endpointed indicated a failure. See InnerException for details.
 ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="state store notification-redis-cache query failed: invalid output")
   at Dapr.Client.DaprClientGrpc.QueryStateAsync[TValue](String storeName, String jsonQuery, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)
```
This works when the query state matches and has data. We expected the query state to return an empty list but instead it throws an error. Is this by design or is it a bug?
