### ISSUE TITLE
Add option for state support to make schedules durable across sidecar restarts 

### ISSUE THREAD

**Issue by mchmarny** [dapr/components-contrib#402]
this would allow Dapr schedules to survive Dapr sidecar restarts. For example:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: run
spec:
  type: bindings.cron
  metadata:
  - name: schedule
    value: "@every 5h"
  - name: statestore
    value: "cron-state" # name of the Dapr registered `state` component 
```
