### ISSUE TITLE
Kubernetes Event Binding with Dapr

### ISSUE THREAD

**Issue by rohi-modak-ct** [dapr/components-contrib#4209]
## In what area(s)?

/area runtime

## Ask your question here

We intend to use kubernetes event binding https://docs.dapr.io/reference/components-reference/supported-bindings/kubernetes-binding/ provided by dapr to get notified of kubernetes events related to kubernetes jobs. 

We were successfully able to get it up and running in our kubernetes cluster following the documentation link above. But, we are getting notified for each and every event that happens in the kubernetes cluster. 
We have python microservices running and the pod which has the endpoint where the events are being sent by dapr is getting hit by a large number of requests every second, so we want to filter the events which it is getting.

Can we only listen to events generated by the kubernetes `api group "batch"` or the `resource "job"`?
In the configuration of the kubernetes event binding, is there a way we can restrict it to notify only for events of kubernetes jobs ?

Also, In addition to the metadata fields mentioned in the documentation https://docs.dapr.io/reference/components-reference/supported-bindings/kubernetes-binding/#spec-metadata-fields are there any other which can be used to achieve this? For example, many other bindings, e.g. Kafka, have support for a much larger number of metadata fields. We have tried with different metadata fields apart from ones in code below (which BTW are not mentioned in the doc and neither did they work) but did not get the desired results.

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: job-events
spec:
  type: bindings.kubernetes
  version: v1
  metadata:
  - name: namespace
    value: "default"
  - name: resyncPeriodInSec
    value: "60"
  - name: direction
    value: "input"
  # - name: resource
  #   value: "jobs"
  # - name: apiVersion
  #   value: "batch/v1"
  - name: resources
    value: "pods"
  - name: labelSelector
    value: "app=pds-app"
```
