### ISSUE TITLE
[Proposal] Database component based on bindings

### ISSUE THREAD

**Issue by rdiaz82** [dapr/components-contrib#441]
# Goal
>Implement a Dapr component to interact with an external database using output/input bindings allowing users to have the freedom to interact with a database in a more rich way.

# Context
The current implementation of Dapr allows users to save the information into the database and it also allows users to get the state from the database only given a key or a group of keys in the case of bulk operations. This way to work is very useful for keeping a state between services call or for applications where data is stored following a key-value architecture.

The limitations of the current implementation arise if the user applications need to perform any kind of query further than get data by Id. If the users need to perform any kind of query they have to perform them using specific database connections outside the Dapr ecosystem and losing all the isolation and encapsulation features provided by Dapr.

# Why Bindings?
According to Dapr definition, bindings are the way to connect to external resources and in this proposal, we are not going to propose to change the current state store implementation because the current implementation as we set in the previous section works smoothly for some specific use cases.

With this proposal, we want to fill the gap and give an option for other applications to have more freedom when they are accessing a database from a Dapr application without losing any of the Dapr advantages.

# The Foundations
The main idea is to create a generic database component on top of a binding component. We can have two types of bindings related to databases:

### Output binding:

* **create**: to save the information inside the database.

* **query**: to perform a query against the database.

* **get**: this can be used to fetch just one element from the database using it id.

* **delete**: to remove specific data from the database.

### Input binding:

to **subscribe** to a possible event **change stream** provided by the database.

# The Query Language
To perform queries we can use a syntax similar to MongoDB based on JSON:

```JSON
{
  "collection": "collectionName",
	"query" : {
  	"field" : "fieldValue"
	}
}
```
This query is the equivalent sql:

```SQL
SELECT * FROM collectionName WHERE field = fieldValue
```

In order to specify `AND` conditions:

```JSON
{
  "collection": "collectionName",
	"query":{
  	"field" : "fieldValue",
  	"field2" : { "$lt": 20}
	}
}
```

The equivalent sql is the following:
```SQL
SELECT * FROM collectionName WHERE field = "fieldValue" AND field2 < 20
```
In order to include operators have introduced it as a JSON object with the structure `{$operatorName: operatorValue}`. To support the `OR` condition we can do it in the following way:

```JSON
{
  "collection": "collectionName",
	"query":{
  	"field" : "fieldValue",
  	"$or" : [{"field2": {"$lt": 20}}, {"field3": {"$gt": 30}}]
	}
}
```
The equivalent sql statement is:
```SQL
SELECT * FROM collectionName WHERE field = "fieldValue" AND ( field2 > 20 OR field3 >30)
```
Regarding the number of operators, we can implement a subset of operators from MongoDB: https://docs.mongodb.com/manual/reference/operator/query/.

# Usage
### Output Binding
As a normal binding we need to define the component specs in a yaml file:
```YAML
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mydatabase
  namespace: <NAMESPACE>
spec:
  type: bindings.database.mongodb
  metadata:
  - name: host
    value: us-west-2
  - name: username
    value: *****************
  - name: password
    value: *****************
```
After applying the yaml file to the cluster we can start to perform calls using the different actions to the database:
```
curl -X POST -H  http://localhost:3500/v1.0/bindings/mydatabase -d 
'{ "data": { 
                   "collectionName": "collectionName", 
		   "data": {
		   		"field1": "value1", 
		   		"field2":"value2"
		   	}
		}, 
   "operation": "create" 
}'
```
In the case of queries we can have this:
```
curl -X POST -H  http://localhost:3500/v1.0/bindings/mydatabase -d 
'{ "data": { 
                   "collectionName": "collectionName", 
		   "data": {
		   		"field1": "value1", 
		   		"field2":{"$gt": 20}
		   	}
		}, 
   "operation": "query" 
}'
```

### Input Binding
Input Binding
The input bindings can be used to get subscribed to the database change stream. We need to provide the event configuration using the yaml file:
```YAML
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mydatabase
  namespace: <NAMESPACE>
spec:
  type: bindings.database.mongodb
  metadata:
  - name: host
    value: us-west-2
  - name: username
    value: *****************
  - name: password
    value: *****************
  - name: collection
  	value: collectionName
  - name: subscriptionType
    value: all #one of [all, save, delete or update]
```

Then the user as other input bindings needs to provide the listening method for the event. More information about the listener implementation here: https://github.com/dapr/docs/tree/v0.10.0/howto/trigger-app-with-input-binding
# Implementation
The database binding component can be implemented just using the current binding component interface just with the implementation of a specific database query parse method that is going to be called from the Invoke method.
```Go
type InputBinding interface {
	Init(metadata Metadata) error
	Read(handler func(*ReadResponse) error) error
}
```
```Go
type OutputBinding interface {
	Init(metadata Metadata) error
	Invoke(req *InvokeRequest) (*InvokeResponse, error)
	Operations() []OperationKind
}
```

What do you think about this implementation? I think that it could help a lot to solve the problem that other people have raised about the use of the state store and queries without changing Dapr core and at the same time in a flexible and extensible way.
