### ISSUE TITLE
EventHub consumer groups not used due to reversed partition metadata logic

### ISSUE THREAD

**Issue by mchmarny** [dapr/components-contrib#445]
## Expected Behavior

Dapr using the set `consumerGroup` metadata in Event Hub component.

## Actual Behavior

EventHub component doesn't use set `consumerGroup` resulting in only one application receiving the events. 

> `P0` as there may be users who currently do not know that their app is missing events

## Steps to Reproduce the Problem

The [specific portion of the Event Hub component code](https://github.com/dapr/components-contrib/blob/c6623da87eaad01af0b9acd7171b478be955e460/bindings/azure/eventhubs/eventhubs.go#L213-L216) responsible for receiving with a consumer group is not being executed.  This appears to be related to the inverse logic in the way the `metadata.partitioned` metadata element is [being interpreted](https://github.com/dapr/components-contrib/blob/c6623da87eaad01af0b9acd7171b478be955e460/bindings/azure/eventhubs/eventhubs.go#L171-L179). 

Currently when `consumerGroup` is set in metadata, line 214 (`eventhubs: using consumer group...`) is not output to Dapr log. When `partitionID` is explicitly set, the code executes as expected.

**Comment by artursouza** [comment]
The logic pointed out in the description is correct and not inverted. I talked to Mark C. and I will focus on reproducing the problem first. The root cause is still TBD.

**Comment by artursouza** [comment]
Changed it to medium since it requires some more investigation.

**Comment by artursouza** [comment]
I used the binding quickstart to replay this scenario. These are the yaml files needed to replay this scenario in kubernetes:

Pre-reqs:
- Create one EventHub namespace + topic.
- Create a storage account and container.

all.yaml
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sample-topic
spec:
  type: bindings.azure.eventhubs
  metadata:
  - name: connectionString
    value: Endpoint=sb://XXXXXX.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=KFknfiVshbBABqtxk+ByJQXfq4brYz95PW416BAC5Fk=;EntityPath=XXXXXXXXXX
  - name: consumerGroup
    value: $Default
  - name: storageAccountName
    value: XXXXXXXX
  - name: storageAccountKey
    value: XXXXXXXXX
  - name: storageContainerName
    value: XXXXXXXXX
---
kind: Service
apiVersion: v1
metadata:
  name: bindings-nodeapp
  labels:
    app: bindingsnodeapp
spec:
  selector:
    app: bindingsnodeapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bindings-nodeapp
  labels:
    app: bindingsnodeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bindingsnodeapp
  template:
    metadata:
      labels:
        app: bindingsnodeapp
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "bindings-nodeapp"
        dapr.io/app-port: "3000"
    spec:
      containers:
      - name: node
        image: docker.io/dapriosamples/bindings-nodeapp:edge
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bindings-pythonapp
  labels:
    app: bindingspythonapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: bindingspythonapp
  template:
    metadata:
      labels:
        app: bindingspythonapp
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "bindings-pythonapp"
    spec:
      containers:
      - name: python
        image: docker.io/dapriosamples/bindings-pythonapp:edge
```

`kubectl apply -f all.yaml`

Wait for 1 minute or two. Then count how many rows are output per subscriber pod:

```sh
$ kubectl  get pods | grep nodeapp | cut -d\  -f1 | xargs -I {} bash -c "kubectl logs {} node | wc -l "
    9053
    9055
   17787
```

Load seems to be somewhat distributed among the pods. One is getting more load but we are not seeing the issue where only one takes load.
