### ISSUE TITLE
use vault secretstore occured error

### ISSUE THREAD

**Issue by dybxin** [dapr/components-contrib#524]
> /area runtime

## Ask your question here
```
level=error msg="error getting secret: couldn't to get successful response: &http.Response{Status:\"403 Forbidden\", StatusCode:403, Proto:\"HTTP/1.1\", ProtoMajor:1, ProtoMinor:1, Header:http.Header{\"Cache-Control\":[]string{\"no-store\"}, \"Content-Length\":[]string{\"33\"}, \"Content-Type\":[]string{\"application/json\"}, \"Date\":[]string{\"Tue, 10 Nov 2020 02:26:59 GMT\"}}, Body:(*http.bodyEOFSignal)(0xc00047ea80), ContentLength:33, TransferEncoding:[]string(nil), Close:false, Uncompressed:false, Trailer:http.Header(nil), Request:(*http.Request)(0xc000322200), TLS:(*tls.ConnectionState)(nil)}, {\"errors\":[\"permission denied\"]}\n" app_id=nodeapp instance=yabing scope=dapr.runtime type=log ver=0.11.2
```
## Additional information
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault
  namespace: default
spec:
  type: secretstores.hashicorp.vault
  metadata:
  - name: vaultAddr
    value: http://127.0.0.1:8200 # Optional. Default: "https://127.0.0.1:8200"
  # - name: caCert # Optional. This or caPath or caPem
  #   value: "[ca_cert]"
  # - name: caPath # Optional. This or CaCert or caPem
  #   value: "[path_to_ca_cert_file]"
  # - name: caPem # Optional. This or CaCert or CaPath
  #   value : "[encoded_ca_cert_pem]"
  # - name: skipVerify # Optional. Default: false
  #   value : "[skip_tls_verification]"
  # - name: tlsServerName # Optional.
  #   value : "[tls_config_server_name]"
  - name: vaultTokenMountPath # Required. Path to token file.
    value : unseal.key
  - name: vaultKVPrefix # Optional. Default: "dapr"
    value : secret
```
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    secretKeyRef:
      name: mysecret
      key: mysecret
  - name: actorStateStore
    value: "true"
auth:
    # secretStore: localsecretstore
    secretStore: vault
```
```js
const app = express();
app.use(bodyParser.json());

const daprPort = process.env.DAPR_HTTP_PORT || 3500;
// const secretStoreName = "localsecretstore"; 
const secretStoreName = "vault"; 
const secretName = 'mysecret'

const secretsUrl = `http://localhost:${daprPort}/v1.0/secrets`;

const port = 3000;

app.get('/getsecret', (_req, res) => {
    const url = `${secretsUrl}/${secretStoreName}/${secretName}?metadata.namespace=default`
    console.log("Fetching URL: %s", url)
    fetch(url)
    .then(res => res.json())
    .then(json => {
        console.log("json:", json)
        let secretBuffer = new Buffer(json["mysecret"])
        let encodedSecret = secretBuffer.toString()
        console.log("Base64 encoded secret is: %s", encodedSecret)
        return res.send(encodedSecret)
    })
});

app.listen(port, () => console.log(`Node App listening on port ${port}!`));
```
```
vault kv put secret/mysecret mysecret=123
```
