### ISSUE TITLE
how-to:Use secrets building block retrieves the secret from the Map structure

### ISSUE THREAD

**Issue by dybxin** [dapr/components-contrib#533]
> /area runtime
> /area docs

## Ask your question here
how-to:Use secrets building block retrieves the secret from the Map structure?

local-secret-store.yaml
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: localsecretstore
  namespace: default
spec:
  type: secretstores.local.file
  metadata:
  - name: secretsFile
    value: secrets.json
  - name: nestedSeparator
    value: ":"
```

secrets.json
```json
{
    "mysecret": "abcd",
    "connectionStrings": {
        "sql": "your sql connection string",
        "mysql": "your mysql connection string"
    }
}
```
after `dapr run `, i use the flattened key to access the secret. 

```
localhost:3500/v1.0/secrets/localsecretstore/connectionStrings:sql
```
i got errorCode: `ERR_STATE_GET`
