### ISSUE TITLE
[Proposal]: make state key prefix configrable

### ISSUE THREAD

**Issue by skyao** [dapr/components-contrib#542]
## Current Design

In state api (both grpc and http) of dapr runtime, dapr will add a prefix in the key for all state operations like get/save/delete.

```go
req := state.GetRequest{
	Key:      a.getModifiedStateKey(param.(string)),
	Metadata: in.Metadata,
}

const  daprSeparator        = "||"
func (a *api) getModifiedStateKey(key string) string {
	if a.id != "" {
		return fmt.Sprintf("%s%s%s", a.id, daprSeparator, key)
	}
	return key
}
```

This feature make all the states within the app (with same app id) can be seperated from other app, even their key is the same. This feature works well in this case.

## Requirement Backgroup

Yet we have some others user case:

1. We need to share states between some apps which are dapr enabled, this key prefix is not needed or should be set to a fixed one (not appid)
2. We need to share states between apps: some are dapr enabled and others are NOT, especaillay for the legecy apps, the key scheme of the state are widely used and can't change to add appid (like dapr)  

Now we are blocked for this key perfix strategy which is hard code in dapr runtime code.

In fact, in a mature destributed state system, the keys are always designed to have their schema which are much complecated then a simgle appid.

## Proposal

Can we make the  state key prefix  configrable ? 

It means that we can add a configuration (or metadata) somewhere, by default it will add appid as key prefix, but we can change this configuration to disable key prefix or set a fix value as prefix.

We need a more **flexible** state sharing strategy for different user cases:

1. Sharing states in globle scope:  no prefix for state key
2. Sharing states in specified scope: uses a fix value as prefix
3. Sharing states only in current app: uses app-id as prefix 

## Implementation Proposal

Where and how to configure this key perfix strategy?  The simplest solution is in state component yaml file: we can add metadata named like "keyPrefix":

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    secretKeyRef:
      name: redissecret
      key: host
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: true
  - name: keyPrefix
    value: ""
```

The value of keyPrefix can be:

- "" or not set : no prefix (defalut case)
- "app-id": uses app-id as prefix 
- "some-other-value": uses this configure value as prefix

or if we want to defalut to use app-id as prefix:

- "" or not set : uses app-id as prefix (defalut case)
- "none": no prefix
- "some-other-value": uses this configure value as prefix
