### ISSUE TITLE
Local file secrets store does not flatten hierarchy correctly

### ISSUE THREAD

**Issue by EdwinVW** [dapr/components-contrib#550]
## Expected Behavior

I use the local file secrets store with the following configuration:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: localfile-secret-store
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: ./components/secrets.json
  - name: nestedSeparator
    value: ":"
```

and the following secrets file:
```json
{
  "passwords": {
    "redis": "Pass@word1"
  }
}
```

The configured `nestedSeparator` is a colon, so I expect to be able to get the value of the secret using the key `passwords:redis`.

This behavior is described in the [dapr docs](https://v1-rc1.docs.dapr.io/operations/components/setup-secret-store/supported-secret-stores/file-secret-store/).

## Actual Behavior

When I try to retrieve the secret using the DaprClient for .NET:

```csharp
DaprClient client = new DaprClientBuilder().Build();
var secrets = await client.GetSecretAsync("localfile-secret-store", "passwords:redis");
```

I get an error that the no secret with key `passwords:redis` can be found:

```
== APP == Unhandled exception. Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="failed getting secret with key passwords:redis from secret store localfile-secret-store: secret passwords:redis not found")
```

When I reference the password from another Dapr component configuration file (e.g. state management): 

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: test-statestore
  namespace: default
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    secretKeyRef:
      name: passwords:redis
      key: passwords:redis
auth:
  secretStore: localfile-secret-store
```

I get an error stating that no secret with the specified key can be found:

```
== DAPR == time="2020-12-06T14:04:00.7653927+01:00" level=error msg="error getting secret: secret passwords:redis not found" app_id=testapp instance=EDWINW01 scope=dapr.runtime type=log ver=1.0.0-rc.1
```

## Steps to Reproduce the Problem

- Make sure you have a Redis instance running on `localhost:6379` that requires a password `Pass@word1`.
- Create a .NET app that uses the local file secrets management component as described in the _Actual Behavior_ section. See [repro-app.zip](https://github.com/dapr/components-contrib/files/5648804/repro-app.zip) for an example.
- Run the application with Dapr (in stand-alone mode) from the application folder:
  ```
  dapr run --app-id testapp --components-path .\components dotnet run
  ```

If you remove the nested hierarchy from the secrets file:

```json
{
  "redisPassword": "Pass@word1"
}
```

and replace all occurrences of the key `passwords:redis` with `redisPassword` in the code and config, the behavior is as expected and the application works fine.

## Release Note

RELEASE NOTE: **FIX** Bug in flattening of JSON hierarchy by local file secrets store.
