### ISSUE TITLE
Middleware component - middleware.http.opa not loading - 1.0.0-rc.2

### ISSUE THREAD

**Issue by slacksach** [dapr/components-contrib#569]
## Expected Behavior

middleware.http.opa loads

## Actual Behavior

`process component opa error: incorrect type middleware.http.opa"
`
## Steps to Reproduce the Problem

1. Add a config referencing a middleware component
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: pipeline
  namespace: default
spec:
  httpPipeline:
    handlers:
    - name: opa
      type: middleware.http.opa
```
2. Add the middleware component using the opa example from the docs. - https://docs.dapr.io/developing-applications/middleware/middleware-opa-policies/ and set the name to: opa
3. dapr run

This line seems to cause the issue as it will always return blank for types not defined in the list - https://github.com/dapr/dapr/blob/dde6a6b834c56d4cc0bd788062c8c64f416d20c8/pkg/runtime/runtime.go#L1353

Observe error.
