### ISSUE TITLE
Azure Storage - File Uploading & Decoding with Base64 API

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/components-contrib#641]
## Expected Behavior

I would like to upload a file with the **Azure Storage Binding**. For this to happen I encode it as Base64 and would like to decode it as soon as it is being saved. I would expect the [`decodeBase64`](https://github.com/dapr/components-contrib/blob/master/bindings/azure/blobstorage/blobstorage.go#L148) feature to take care of this.

## Actual Behavior

I expect:
1. The Base64 decoding is not working for me (I might have it wrongly configured, but I checked it to my knowledge)
2. Get the BlobURL back (this is for me on undefined)

## Steps to Reproduce the Problem

**Binding YAML**

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: binding-azure-storage-screenshots
  namespace: default
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
  - name: storageAccount
    value: A_MASKED_SA
  - name: storageAccessKey
    value: A_MASKED_ACCESS_KEY
  - name: container
    value: screenshotsfor read blob access
  - name: decodeBase64
    value: "true"
```

Whereafter I try to save a file through the following Javascript code:

```javascript
const res = await fetch(`http://localhost:3500/v1.0/bindings/my-azure-binding`, {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({
    operation: 'create',
    data: "FILE_BASE64",
    metadata: {
        "ContentType": "image/jpeg",
        "blobName": "my-test-img.jpg"
    }
  }),
});
```

When inspecting the `res` object it returns "undefined" after utilizing `await res.text()`; `await res.json()` returns an error as expected. The status code however is `200` 

Finally I would like to note that:
1. The file gets created in Azure
2. The Base64 content is written (but not the decoded content as expected with the metadata flag in the YAML file)
3. File name + MIME + extension are correct 

## Release Note

Dapr v1 RC .2

**FIX** Base64 file decoding
**FIX** `blobURL` not being returned after file creation

RELEASE NOTE:
