### ISSUE TITLE
redisPassword not working in Redis Sentinel State Store

### ISSUE THREAD

**Issue by Syuparn** [dapr/components-contrib#756]
## Expected Behavior

Redis Sentinel can be used for Redis State Store component. Master's password can be configured with component's `redisPassword` metadata.

## Actual Behavior

When sentinel master has a password, dapr sidecar fails to initialize with Redis authentication error even though component's `redisPassword` is same as the master's one.

## Steps to Reproduce the Problem

This sample is based on [dapr/samples hello-docker-compose](https://github.com/dapr/samples/tree/master/hello-docker-compose).

- `docker-compose.yml`

```yaml
# ...
# replace Redis with Redis Sentinel
  ############################
  # Redis state store
  ############################
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - "6380:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=str0ng_passw0rd
    networks:
      - hello-dapr
  redis-replica:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=replica
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
    networks:
      - hello-dapr
  redis-sentinel-1:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
    depends_on:
      - redis
      - redis-replica
    networks:
      - hello-dapr
  redis-sentinel-2:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
    depends_on:
      - redis
      - redis-replica
    networks:
      - hello-dapr
  redis-sentinel-3:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
    depends_on:
      - redis
      - redis-replica
    networks:
      - hello-dapr
# ...
```

- `components/statestore.yaml`

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-sentinel-1:26379
  - name: redisPassword
    value: str0ng_passw0rd # redis master's password
  - name: failover
    value: true
  - name: sentinelMasterName
    value: mymaster # default of bitnami/redis-sentinel
```

- Also set the password to `components/pubsub.yaml`

Result: 

```bash
$ docker-compose up -d
$ $ docker-compose ps
               Name                             Command               State                  Ports              
----------------------------------------------------------------------------------------------------------------
hello-docker-compose_nodeapp-        ./daprd -app-id nodeapp -a ...   Exit 1                                    
dapr_1                                                                                                          
hello-docker-compose_nodeapp_1       docker-entrypoint.sh node  ...   Up       3000/tcp,                        
                                                                               0.0.0.0:50002->50002/tcp         
hello-docker-compose_placement_1     ./placement -port 50006          Up       0.0.0.0:50006->50006/tcp         
hello-docker-compose_pythonapp-      ./daprd -app-id pythonapp  ...   Exit 1                                    
dapr_1                                                                                                          
hello-docker-compose_pythonapp_1     python app.py                    Up                                        
hello-docker-compose_redis-          /opt/bitnami/scripts/redis ...   Up       6379/tcp                         
replica_1                                                                                                       
hello-docker-compose_redis-          /opt/bitnami/scripts/redis ...   Up       26379/tcp                        
sentinel-1_1                                                                                                    
hello-docker-compose_redis-          /opt/bitnami/scripts/redis ...   Up       26379/tcp                        
sentinel-2_1                                                                                                    
hello-docker-compose_redis-          /opt/bitnami/scripts/redis ...   Up       26379/tcp                        
sentinel-3_1                                                                                                    
hello-docker-compose_redis_1         /opt/bitnami/scripts/redis ...   Up       0.0.0.0:6380->6379/tcp
$ docker-compose logs --tail 5 nodeapp-dapr
Attaching to hello-docker-compose_nodeapp-dapr_1
nodeapp-dapr_1      | time="2021-03-14T03:05:21.82797739Z" level=info msg="component loaded. name: pubsub, type: pubsub.redis/v1" app_id=nodeapp instance=9b6d7a53a1e9 scope=dapr.runtime type=log ver=edge
nodeapp-dapr_1      | time="2021-03-14T03:05:21.828503586Z" level=info msg="waiting for all outstanding components to be processed" app_id=nodeapp instance=9b6d7a53a1e9 scope=dapr.runtime type=log ver=edge
nodeapp-dapr_1      | time="2021-03-14T03:05:21.903007857Z" level=warning msg="error initializing state store statestore (state.redis/v1): redis store: error connecting to redis at redis-sentinel-1:26379: NOAUTH Authentication required." app_id=nodeapp instance=9b6d7a53a1e9 scope=dapr.runtime type=log ver=edge
nodeapp-dapr_1      | time="2021-03-14T03:05:21.903161706Z" level=fatal msg="process component statestore error: redis store: error connecting to redis at redis-sentinel-1:26379: NOAUTH Authentication required." app_id=nodeapp instance=9b6d7a53a1e9 scope=dapr.runtime type=log ver=edge
nodeapp-dapr_1      | redis: 2021/03/14 03:05:21 sentinel.go:435: sentinel: new master="mymaster" addr="172.24.0.3:6379"
```

## Release Note

RELEASE NOTE: **FIX** Password configuration for Redis Sentinel state store.
