### ISSUE TITLE
Refactor Bindings conformance test

### ISSUE THREAD

**Issue by mukundansundar** [dapr/components-contrib#775]
## Describe the proposal
Right now the conformance tests for bindings tests the following operations as seen in https://github.com/dapr/components-contrib/blob/master/tests/conformance/bindings/bindings.go#L96: 
- `operations`
- `Get`
- `Create`
- `List`
- `Delete`
and `read` to verify reading from the binding.

Almost all of the operations themselves only call the Invoke() API on the binding with the corresponding operation name. 

To make the conformance test more versatile and configurable for different bindings (operations with name `exec` etc.), the ideal scenario would be that the the conformance tests can be configured to run 
- `operations` 
- `invoke` 
API tests. Additional configuration needs to be provided specific to each binding for example, 
```yaml
  component: azure.blobstorage
  operations: ["create", "operations", "get"]
  config:
    output:
    blobName: $((uuid))
```
instead of the operations being `["create", "operations", "get"]`, it will only be `["invoke", "operations"]`

Additional fields in the config map can be there to specify that it needs to be tested for `["create", "get"]` operations. 

This way, when we want to support other bindings which do not plainly support only `create` and `get`, we can add new tests and add it as a configuration parameter. 

@artursouza @pkedy Thoughts on this?

**Comment by pkedy** [comment]
Sorry this is probably in left field because I don't fully understand the question yet but...

If you are thinking of something like `mapstructure` for the config, would the operations fit into the config too? Wondering if it could be generic at the "runner" level like this:

```yaml
type: input_binding
config:
  component: azure.blobstorage
  invoke: ["create", "operations", "get"]
  output:
    blobName: $((uuid))
```

I'm probably not answering your primary question yet but at least wanted to start with this concept of pushing configuration details into the "runner" implementation. Taking a deeper look at the existing code/structure now...
