### ISSUE TITLE
Http Output Cache Feature

### ISSUE THREAD

**Issue by mstrYoda** [dapr/components-contrib#783]
## Describe the proposal

It would be nice to add http output cache feature. Dapr already has state management. With a new component type users can define caching feature in front of some endpoints.

I am volunteer to implement that feature if it accepted.

I imagine some configuration with a component resource like:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cachestore
  namespace: default
spec:
  type: cache.<DATABASE>
  version: v1
  metadata:
  - name: resource1
     value: /some/endpoint
  - name: cacheTTL
     value: 30m
scopes:
- my-app
```

or as a middleware:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-app-cache
  namespace: default
spec:
  type: middleware.http.cache
  version: v1
  metadata:
  - name: resource1
     value: /some/endpoint
  - name: cacheTTL
     value: 30m
scopes:
- my-app
```
