### ISSUE TITLE
Configuration bearer component with azure ad results in dapr sidecar crash

### ISSUE THREAD

**Issue by denniszielke** [dapr/components-contrib#848]
## Expected Behavior

Bearer component middleware with azure ad should work

## Actual Behavior

Bearer component middleware component configuration with azure ad seems to crash dapr sidecar

## Steps to Reproduce the Problem

dapr configuration
```
dapr status -k 
  NAME                   NAMESPACE    HEALTHY  STATUS   REPLICAS  VERSION  AGE  CREATED              
  dapr-sidecar-injector  dapr-system  True     Running  1         1.1.2    2d   2021-04-26 09:53.23  
  dapr-placement-server  dapr-system  True     Running  1         1.1.2    2d   2021-04-26 09:53.23  
  dapr-sentry            dapr-system  True     Running  1         1.1.2    2d   2021-04-26 09:53.23  
  dapr-operator          dapr-system  True     Running  1         1.1.2    2d   2021-04-26 09:53.23  
  dapr-dashboard         dapr-system  True     Running  1         0.6.0    2d   2021-04-26 09:53.23  
```

create azure ad app
```
API_APP_NAME=dapr-demo-app1
TENANT_ID=$(az account show --query tenantId -o tsv)
API_APP_URI_ID=https://$TENANT_NAME/$API_APP_NAME
API_APP_ID=$(az ad app create --display-name $API_APP_NAME --homepage http://localhost --identifier-uris $API_APP_URI_ID  -o json | jq -r '.appId')
APP_NAMESPACE="bearer"
kubectl create ns $APP_NAMESPACE
```

created bearer component
```
cat <<EOF | kubectl apply -f -  
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: bearer-token
  namespace: $APP_NAMESPACE
spec:
  type: middleware.http.bearer
  version: v1
  metadata:
  - name: clientId
    value: "$API_APP_ID"
  - name: issuerURL
    value: "https://sts.windows.net/$TENANT_ID/"
EOF
```

created bearer configuration

```
cat <<EOF | kubectl apply -f -  
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: bearer-config
  namespace: $APP_NAMESPACE
spec:
  httpPipeline:
    handlers:
    - name: bearer-token
      type: middleware.http.bearer
EOF
```

created deployment using the configuration

```
cat <<EOF | kubectl apply -f -  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-logger-bearer
  namespace: $APP_NAMESPACE
spec:
  replicas: 1 
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  selector:
    matchLabels:
      app: dummy-logger
  template:
    metadata:
      labels:
        app: dummy-logger
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dummy-logger-bearer"
        dapr.io/app-port: "80"
        dapr.io/config: "bearer-config"
        dapr.io/log-as-json: "true"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: dummy-logger
        image: denniszielke/dummy-logger:latest  
        ports:
        - containerPort: 80
        imagePullPolicy: Always   
EOF

```

container starts crash looping and this is the log of the dapr sidecar

```
kubectl logs dummy-logger-bearer-5c6d54ff95-hllw5  -n bearer daprd                                              
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"info","msg":"starting Dapr Runtime -- version 1.1.2 -- commit 3148f36","scope":"dapr.runtime","time":"2021-04-28T16:02:20.308622204Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"info","msg":"log level set to: debug","scope":"dapr.runtime","time":"2021-04-28T16:02:20.308713607Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"info","msg":"metrics server started on :9090/","scope":"dapr.metrics","time":"2021-04-28T16:02:20.308936414Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"debug","msg":"No Access control policy specified","scope":"dapr.configuration","time":"2021-04-28T16:02:20.352296594Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"info","msg":"kubernetes mode configured","scope":"dapr.runtime","time":"2021-04-28T16:02:20.352509101Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"info","msg":"app id: dummy-logger-bearer","scope":"dapr.runtime","time":"2021-04-28T16:02:20.352635406Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"info","msg":"mTLS enabled. creating sidecar authenticator","scope":"dapr.runtime","time":"2021-04-28T16:02:20.352946016Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"info","msg":"trust anchors and cert chain extracted successfully","scope":"dapr.runtime.security","time":"2021-04-28T16:02:20.353128122Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"info","msg":"authenticator created","scope":"dapr.runtime","time":"2021-04-28T16:02:20.353154223Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"info","msg":"Initialized name resolution to kubernetes","scope":"dapr.runtime","time":"2021-04-28T16:02:20.353559337Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"debug","msg":"loading component. name: kubernetes, type: secretstores.kubernetes/v1","scope":"dapr.runtime","time":"2021-04-28T16:02:20.353758244Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"info","msg":"component loaded. name: kubernetes, type: secretstores.kubernetes/v1","scope":"dapr.runtime","time":"2021-04-28T16:02:20.355744412Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"debug","msg":"found component. name: bearer-token, type: middleware.http.bearer/v1","scope":"dapr.runtime","time":"2021-04-28T16:02:20.362596946Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"debug","msg":"found component. name: oauth2, type: middleware.http.oauth2/v1","scope":"dapr.runtime","time":"2021-04-28T16:02:20.362626047Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"debug","msg":"found component. name: my-oauth-component, type: middleware.http.oauth2clientcredentials/v1","scope":"dapr.runtime","time":"2021-04-28T16:02:20.362637147Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"debug","msg":"found component. name: my-oauth-component, type: middleware.http.oauth2clientcredentials/v1","scope":"dapr.runtime","time":"2021-04-28T16:02:20.362689149Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"debug","msg":"found component. name: bearer-token, type: middleware.http.bearer/v1","scope":"dapr.runtime","time":"2021-04-28T16:02:20.362700449Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"info","msg":"waiting for all outstanding components to be processed","scope":"dapr.runtime","time":"2021-04-28T16:02:20.36271395Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"debug","msg":"loading component. name: bearer-token, type: middleware.http.bearer/v1","scope":"dapr.runtime","time":"2021-04-28T16:02:20.362770552Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"info","msg":"component loaded. name: bearer-token, type: middleware.http.bearer/v1","scope":"dapr.runtime","time":"2021-04-28T16:02:20.362811753Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"info","msg":"all outstanding components processed","scope":"dapr.runtime","time":"2021-04-28T16:02:20.362906756Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"info","msg":"enabled middleware.http.bearer/ http middleware","scope":"dapr.runtime","time":"2021-04-28T16:02:20.711610857Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"info","msg":"enabled gRPC tracing middleware","scope":"dapr.runtime.grpc.api","time":"2021-04-28T16:02:20.711723661Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"info","msg":"enabled gRPC metrics middleware","scope":"dapr.runtime.grpc.api","time":"2021-04-28T16:02:20.711761462Z","type":"log","ver":"1.1.2"}
{"app_id":"dummy-logger-bearer","instance":"dummy-logger-bearer-5c6d54ff95-hllw5","level":"info","msg":"API gRPC server is running on port 50001","scope":"dapr.runtime","time":"2021-04-28T16:02:20.711817564Z","type":"log","ver":"1.1.2"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16bde9a]

goroutine 1 [running]:
github.com/dapr/dapr/pkg/middleware/http.Pipeline.Apply(0xc0004a2048, 0x1, 0x1, 0xc00020c900, 0x1)
	/home/runner/work/dapr/dapr/pkg/middleware/http/http_pipeline.go:26 +0x3a
github.com/dapr/dapr/pkg/http.(*server).useComponents(...)
	/home/runner/work/dapr/dapr/pkg/http/server.go:106
github.com/dapr/dapr/pkg/http.(*server).StartNonBlocking(0xc0003ca0b0)
	/home/runner/work/dapr/dapr/pkg/http/server.go:60 +0x67
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).startHTTPServer(0xc0001dcd80, 0xdac, 0x1e61, 0x3b4d100, 0x1, 0xc0004a2048, 0x1, 0x1)
	/home/runner/work/dapr/dapr/pkg/runtime/runtime.go:720 +0x4bc
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).initRuntime(0xc0001dcd80, 0xc000324160, 0xa, 0xc000320790)
	/home/runner/work/dapr/dapr/pkg/runtime/runtime.go:324 +0x626
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).Run(0xc0001dcd80, 0xc0005dff40, 0x7, 0x7, 0x5f, 0xc000102000)
	/home/runner/work/dapr/dapr/pkg/runtime/runtime.go:204 +0x25e
main.main()
	/home/runner/work/dapr/dapr/cmd/daprd/main.go:134 +0xf9f

```

## Release Note

RELEASE NOTE:
