### ISSUE TITLE
Enable logging of AAD pod identity for Azure component authentication

### ISSUE THREAD

**Issue by nmeisenzahl** [dapr/components-contrib#903]
I would like to suggest improving the error handling for the AKV (Azure Key Vault) secret store component when using Managed Identity. 

Managed Identity uses [AAD Pod Identity](https://github.com/Azure/aad-pod-identity) to authenticate against the AKV. To do so you will need to map the Selector from the AzureIdentityBindings resources within the Deployment/Pod you would like to use it.

``` yaml
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: test-identity-binding
spec:
  azureIdentity: test-identity
  selector: test-identity
```

``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app
  name: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      annotations:
        dapr.io/app-id: test-app
        dapr.io/enabled: "true"
      creationTimestamp: null
      labels:
        aadpodidbinding: test-identity
        app: test-app
    spec:
      containers:
      ....
```

If the selector "test-identity" from the Binding does not match the "aadpodidbinding" label in the deployment AAD Pod Identity will not work. 

In case of wrong mapping, the Dapr sidecar will successfully start, the component will be loaded and no errors are displayed within the logs (with debugging enabled). Of course, you will be unable to retrieve any secrets. The request gets no response and runs into a timeout. 

I tested this via curl: `curl http://localhost:3500/v1.0/secrets/<akv>/bulk` with Dapr 1.2

I suggest implementing better error handling and output to allow easier debugging.
