### ISSUE TITLE
Secret Stores: AWS: Secret Manager: Receiving a string into the json instead of the pair Key-Value

### ISSUE THREAD

**Issue by MotaOcimar** [dapr/components-contrib#912]
## Expected Behavior
According to the [documentation](https://docs.dapr.io/reference/api/secrets_api/#response-with-multiple-keys-in-a-secret-eg-kubernetes), was expected to recieve a json in the following format:
```json
{
  "key": "value"
}
```

## Actual Behavior
I'm receiving a json in the folowing format:
```json
{
   "db-secret": "`{\"key\":\"value\"}`"
}
```

## Steps to Reproduce the Problem
My component configuration file:
<details>
  <summary>awssecretmanager.yaml</summary>

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: awssecretmanager
  namespace: default
spec:
  type: secretstores.aws.secretmanager
  version: v1
  metadata:
  - name: region
    value: "[my_aws_region]"
  - name: accessKey
    value: "[my_aws_access_key]"
  - name: secretKey
    value: "[my_aws_secret_key]"
```
</details>

My node aplication:
<details>
  <summary>app.js</summary>

```js
const express = require('express');
require('isomorphic-fetch');

const app = express();
const port = 3000;

const daprPort = process.env.DAPR_HTTP_PORT || 3500;
const secretStoreName = "awssecretmanager";
const secretsUrl = `http://localhost:${daprPort}/v1.0/secrets/${secretStoreName}`;

const secretName = 'db-secret'
const url = `${secretsUrl}/${secretName}`

app.get('/logsecret', (_req, res) => {
    console.log("Fetching URL: %s", url)
    fetch(url)
    .then(resp => resp.json())
    .then(json => {
        console.log(json);
        res.send();
    })
});

app.listen(port, () => console.log(`Node App listening on port ${port}!`));
```
</details>

## Release Note

RELEASE NOTE:
