### ISSUE TITLE
Process component vault error

### ISSUE THREAD

**Issue by attiqeurrehman** [dapr/components-contrib#966]
## Expected Behavior

Able to start and consume the vault secret store.

## Actual Behavior

Getting the following error:

```
failed to init state store secretstores.hashicorp.vault/v1 named vault: couldn't create client using config: couldn't read system certs: crypto/x509: system root pool is not available on Windows

process component vault error: couldn't create client using config: couldn't read system certs: crypto/x509: system root pool is not available on Windows
```

## Steps to Reproduce the Problem

1. Install vault on docker `docker run --cap-add=IPC_LOCK -d --name=dev-vault vault`
2. Initialize  `dapr init --slim`
3. Add vault secret store in the components: 
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault
  namespace: default
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
  - name: vaultAddr
    value: http://127.0.0.1:8200
  - name: vaultToken # Required if vaultTokenMountPath not provided. Token value.
    value : s.hJiBv4VaKgsWNEik9BjAfHoQ
```

## Release Note

RELEASE NOTE: FIX

**Comment by daixiang0** [comment]
Please check [it](https://stackoverflow.com/questions/41840307/warning-about-system-root-certificate-pool-crypto-x509/42313975), seems it is caused by docker at windows.

**Comment by attiqeurrehman** [comment]
installed but didn't work and docker is up to date as well.

**Comment by attiqeurrehman** [comment]
@daixiang0 any update on it? docker cli doesn't give me error.

```
docker --version
Docker version 20.10.7, build f0df350
```

**Comment by daixiang0** [comment]
Set log level as debug and share logs please.

**Comment by Taction** [comment]
@attiqeurrehman Please try to set `skipVerify` metadata to true.

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault
  namespace: default
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
  - name: vaultAddr
    value: "http://127.0.0.1:8200"
  - name: vaultToken # Required if vaultTokenMountPath not provided. Token value.
    value : omitted
  - name: skipVerify
    value : "true"
```

The full document about hashicorp vault secret store is [here](https://docs.dapr.io/reference/components-reference/supported-secret-stores/hashicorp-vault/).

**Comment by attiqeurrehman** [comment]
@Taction tried with skipVerify and result is same. 

@daixiang0 following are the logs: 

```
dapr run --app-id myapp --dapr-http-port 3500 --log-level debug
WARNING: no application command found.
Starting Dapr with id myapp. HTTP Port: 3500. gRPC Port: 57021
Checking if Dapr sidecar is listening on HTTP port 3500
time="2021-07-14T14:09:35.7806688+02:00" level=info msg="starting Dapr Runtime -- version 1.2.0 -- commit 8e960e2" app_id=myapp instance=Uzmaki-PC scope=dapr.runtime type=log ver=1.2.0
time="2021-07-14T14:09:35.7806688+02:00" level=info msg="log level set to: debug" app_id=myapp instance=Uzmaki-PC scope=dapr.runtime type=log ver=1.2.0
time="2021-07-14T14:09:35.7816675+02:00" level=info msg="metrics server started on :57022/" app_id=myapp instance=Uzmaki-PC scope=dapr.metrics type=log ver=1.2.0
time="2021-07-14T14:09:35.8006678+02:00" level=info msg="standalone mode configured" app_id=myapp instance=Uzmaki-PC scope=dapr.runtime type=log ver=1.2.0
time="2021-07-14T14:09:35.8006678+02:00" level=info msg="app id: myapp" app_id=myapp instance=Uzmaki-PC scope=dapr.runtime type=log ver=1.2.0
time="2021-07-14T14:09:35.8016688+02:00" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=myapp instance=Uzmaki-PC scope=dapr.runtime type=log ver=1.2.0
time="2021-07-14T14:09:35.8418254+02:00" level=info msg="local service entry announced: myapp -> 192.168.1.7:57027" app_id=myapp instance=Uzmaki-PC scope=dapr.contrib type=log ver=1.2.0
time="2021-07-14T14:09:35.8446482+02:00" level=info msg="Initialized name resolution to mdns" app_id=myapp instance=Uzmaki-PC scope=dapr.runtime type=log ver=1.2.0
time="2021-07-14T14:09:35.8469055+02:00" level=debug msg="found component. name: dev-vault, type: secretstores.hashicorp.vault/v1" app_id=myapp instance=Uzmaki-PC scope=dapr.runtime type=log ver=1.2.0
time="2021-07-14T14:09:35.8478484+02:00" level=debug msg="found component. name: my-secret-store, type: secretstores.local.file/v1" app_id=myapp instance=Uzmaki-PC scope=dapr.runtime type=log ver=1.2.0
time="2021-07-14T14:09:35.8478484+02:00" level=debug msg="found component. name: pubsub, type: pubsub.redis/v1" app_id=myapp instance=Uzmaki-PC scope=dapr.runtime type=log ver=1.2.0
time="2021-07-14T14:09:35.8478484+02:00" level=debug msg="found component. name: statestore, type: state.redis/v1" app_id=myapp instance=Uzmaki-PC scope=dapr.runtime type=log ver=1.2.0
time="2021-07-14T14:09:35.8478484+02:00" level=debug msg="loading component. name: dev-vault, type: secretstores.hashicorp.vault/v1" app_id=myapp instance=Uzmaki-PC scope=dapr.runtime type=log ver=1.2.0
time="2021-07-14T14:09:35.8483753+02:00" level=warning msg="failed to init state store secretstores.hashicorp.vault/v1 named dev-vault: couldn't create client using config: couldn't read system certs: crypto/x509: system root pool is not available on Windows" app_id=myapp instance=Uzmaki-PC scope=dapr.runtime type=log ver=1.2.0
time="2021-07-14T14:09:35.8483753+02:00" level=fatal msg="process component dev-vault error: couldn't create client using config: couldn't read system certs: crypto/x509: system root pool is not available on Windows" app_id=myapp instance=Uzmaki-PC scope=dapr.runtime type=log ver=1.2.0
The daprd process exited with error code: exit status 1
```

**Comment by manishvicky** [comment]
Using following steps I have resolved issues
1)Created PEM file
2)Set caPath metadata to the path to a PEM file

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault
  namespace: default
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:  
  - name: vaultAddr
    value: http://127.0.0.1:8200
  - name: caPath
    value: E:/File/local.pem  
  - name: vaultToken
    value : omitted
  - name: skipVerify
    value: true
```
