### ISSUE TITLE
secretstores.aws.parameterstore fails to be consumed by daprd

### ISSUE THREAD

**Issue by amimimor** [dapr/components-contrib#978]
## Expected Behavior
daprd should have successfully utilized the `secretstores.aws.parameterstore`

## Actual Behavior
after the creation of the `secretstores.aws.parameterstore` component the daprd container outputs:
```
time="2021-06-28T10:01:08.641867105Z" level=warning msg="failed creating secret store secretstores.aws.parameterstore/v1: couldn't find secret store secretstores.aws.parameterstore/v1" app_id=nodeapp instance=nodeapp-65bcff6bf9-v72kx scope=dapr.runtime type=log ver=1.2.2
time="2021-06-28T10:01:08.641953987Z" level=fatal msg="process component parameterstore error: couldn't find secret store secretstores.aws.parameterstore/v1" app_id=nodeapp instance=nodeapp-65bcff6bf9-v72kx scope=dapr.runtime type=log ver=1.2.2
```

## Steps to Reproduce the Problem
* using the following k8s cli and EKS cluster:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.17-eks-c5067d", GitCommit:"c5067dd1eb324e934de1f5bd4c593b3cddc19d88", GitTreeState:"clean", BuildDate:"2021-03-05T23:39:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

* deploy dapr using helm:
```
helm upgrade --install dapr dapr/dapr \
   --version=1.2.2 \
   --namespace dapr-system \
   --create-namespace \
   --wait
```

* deploy the `secretstores.aws.parameterstore` component:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: parameterstore
  namespace: default
spec:
  type: secretstores.aws.parameterstore
  version: v1
  metadata:
  - name: region
    value: "#########"
  - name: accessKey
    value: "#########"
  - name: secretKey
    value: "#########"
```

* then create any dapr based app and verify that the daprd is restarting due to the above-provided error
* I verified, using: 
```
AWS_ACCESS_KEY_ID=xxxxxxxxxx AWS_SECRET_ACCESS_KEY=xxxxxxxxxxxx AWS_DEFAULT_REGION=xxxxxxxx go test -v parameterstore_integ_test.go parameterstore.go
``` 
.... that the component with my credentials works in fetching SSM based key:value and I've applied the same credentials in the Component metadata so I'm assuming the issue is not related the access control/creds 

* digging around `daprd` source, specifically [at the loading of the SecretStores](https://github.com/dapr/dapr/blob/23f2de831fba21c7f855f4315f5d592bed458091/cmd/daprd/main.go#L149) it appears that there is no loading of `aws.parameterstore` component. Might be this the reason the daprd sidecar fails to load this component ? 
## Release Note

RELEASE NOTE: Enables reference to secretstores.aws.parameterstore
